package com.autumnsinger.dal.mapper;

import com.autumnsinger.dal.model.AtomicTask;
import com.autumnsinger.dal.model.AtomicTaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AtomicTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table atomic_task
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    long countByExample(AtomicTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table atomic_task
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    int deleteByExample(AtomicTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table atomic_task
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table atomic_task
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    int insert(AtomicTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table atomic_task
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    int insertSelective(AtomicTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table atomic_task
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    List<AtomicTask> selectByExample(AtomicTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table atomic_task
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    AtomicTask selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table atomic_task
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    int updateByExampleSelective(@Param("record") AtomicTask record, @Param("example") AtomicTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table atomic_task
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    int updateByExample(@Param("record") AtomicTask record, @Param("example") AtomicTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table atomic_task
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    int updateByPrimaryKeySelective(AtomicTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table atomic_task
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    int updateByPrimaryKey(AtomicTask record);
}