package com.autumnsinger.dal.mapper;

import com.autumnsinger.dal.model.FundProductInfo;
import com.autumnsinger.dal.model.FundProductInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FundProductInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_product_info
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    long countByExample(FundProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_product_info
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    int deleteByExample(FundProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_product_info
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_product_info
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    int insert(FundProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_product_info
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    int insertSelective(FundProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_product_info
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    List<FundProductInfo> selectByExample(FundProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_product_info
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    FundProductInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_product_info
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    int updateByExampleSelective(@Param("record") FundProductInfo record, @Param("example") FundProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_product_info
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    int updateByExample(@Param("record") FundProductInfo record, @Param("example") FundProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_product_info
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    int updateByPrimaryKeySelective(FundProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_product_info
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    int updateByPrimaryKey(FundProductInfo record);
}