package com.autumnsinger.dal.mapper;

import com.autumnsinger.dal.model.JijinDaily;
import com.autumnsinger.dal.model.JijinDailyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JijinDailyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jijin_daily
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    long countByExample(JijinDailyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jijin_daily
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    int deleteByExample(JijinDailyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jijin_daily
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jijin_daily
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    int insert(JijinDaily record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jijin_daily
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    int insertSelective(JijinDaily record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jijin_daily
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    List<JijinDaily> selectByExample(JijinDailyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jijin_daily
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    JijinDaily selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jijin_daily
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    int updateByExampleSelective(@Param("record") JijinDaily record, @Param("example") JijinDailyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jijin_daily
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    int updateByExample(@Param("record") JijinDaily record, @Param("example") JijinDailyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jijin_daily
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    int updateByPrimaryKeySelective(JijinDaily record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jijin_daily
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    int updateByPrimaryKey(JijinDaily record);
}