package com.autumnsinger.dal.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FundProductInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fund_product_info
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fund_product_info
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fund_product_info
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    protected List<Criteria> oredCriteria;

    private Integer limit;

    private Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_product_info
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public FundProductInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_product_info
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_product_info
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_product_info
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_product_info
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_product_info
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_product_info
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_product_info
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_product_info
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_product_info
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_product_info
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fund_product_info
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProductCodeIsNull() {
            addCriterion("product_code is null");
            return (Criteria) this;
        }

        public Criteria andProductCodeIsNotNull() {
            addCriterion("product_code is not null");
            return (Criteria) this;
        }

        public Criteria andProductCodeEqualTo(String value) {
            addCriterion("product_code =", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeNotEqualTo(String value) {
            addCriterion("product_code <>", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeGreaterThan(String value) {
            addCriterion("product_code >", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeGreaterThanOrEqualTo(String value) {
            addCriterion("product_code >=", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeLessThan(String value) {
            addCriterion("product_code <", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeLessThanOrEqualTo(String value) {
            addCriterion("product_code <=", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeLike(String value) {
            addCriterion("product_code like", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeNotLike(String value) {
            addCriterion("product_code not like", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeIn(List<String> values) {
            addCriterion("product_code in", values, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeNotIn(List<String> values) {
            addCriterion("product_code not in", values, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeBetween(String value1, String value2) {
            addCriterion("product_code between", value1, value2, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeNotBetween(String value1, String value2) {
            addCriterion("product_code not between", value1, value2, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNull() {
            addCriterion("product_name is null");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNotNull() {
            addCriterion("product_name is not null");
            return (Criteria) this;
        }

        public Criteria andProductNameEqualTo(String value) {
            addCriterion("product_name =", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotEqualTo(String value) {
            addCriterion("product_name <>", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThan(String value) {
            addCriterion("product_name >", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThanOrEqualTo(String value) {
            addCriterion("product_name >=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThan(String value) {
            addCriterion("product_name <", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThanOrEqualTo(String value) {
            addCriterion("product_name <=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLike(String value) {
            addCriterion("product_name like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotLike(String value) {
            addCriterion("product_name not like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameIn(List<String> values) {
            addCriterion("product_name in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotIn(List<String> values) {
            addCriterion("product_name not in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameBetween(String value1, String value2) {
            addCriterion("product_name between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotBetween(String value1, String value2) {
            addCriterion("product_name not between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductTypeIsNull() {
            addCriterion("product_type is null");
            return (Criteria) this;
        }

        public Criteria andProductTypeIsNotNull() {
            addCriterion("product_type is not null");
            return (Criteria) this;
        }

        public Criteria andProductTypeEqualTo(String value) {
            addCriterion("product_type =", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeNotEqualTo(String value) {
            addCriterion("product_type <>", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeGreaterThan(String value) {
            addCriterion("product_type >", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeGreaterThanOrEqualTo(String value) {
            addCriterion("product_type >=", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeLessThan(String value) {
            addCriterion("product_type <", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeLessThanOrEqualTo(String value) {
            addCriterion("product_type <=", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeLike(String value) {
            addCriterion("product_type like", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeNotLike(String value) {
            addCriterion("product_type not like", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeIn(List<String> values) {
            addCriterion("product_type in", values, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeNotIn(List<String> values) {
            addCriterion("product_type not in", values, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeBetween(String value1, String value2) {
            addCriterion("product_type between", value1, value2, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeNotBetween(String value1, String value2) {
            addCriterion("product_type not between", value1, value2, "productType");
            return (Criteria) this;
        }

        public Criteria andNetWorthIsNull() {
            addCriterion("net_worth is null");
            return (Criteria) this;
        }

        public Criteria andNetWorthIsNotNull() {
            addCriterion("net_worth is not null");
            return (Criteria) this;
        }

        public Criteria andNetWorthEqualTo(BigDecimal value) {
            addCriterion("net_worth =", value, "netWorth");
            return (Criteria) this;
        }

        public Criteria andNetWorthNotEqualTo(BigDecimal value) {
            addCriterion("net_worth <>", value, "netWorth");
            return (Criteria) this;
        }

        public Criteria andNetWorthGreaterThan(BigDecimal value) {
            addCriterion("net_worth >", value, "netWorth");
            return (Criteria) this;
        }

        public Criteria andNetWorthGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("net_worth >=", value, "netWorth");
            return (Criteria) this;
        }

        public Criteria andNetWorthLessThan(BigDecimal value) {
            addCriterion("net_worth <", value, "netWorth");
            return (Criteria) this;
        }

        public Criteria andNetWorthLessThanOrEqualTo(BigDecimal value) {
            addCriterion("net_worth <=", value, "netWorth");
            return (Criteria) this;
        }

        public Criteria andNetWorthIn(List<BigDecimal> values) {
            addCriterion("net_worth in", values, "netWorth");
            return (Criteria) this;
        }

        public Criteria andNetWorthNotIn(List<BigDecimal> values) {
            addCriterion("net_worth not in", values, "netWorth");
            return (Criteria) this;
        }

        public Criteria andNetWorthBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("net_worth between", value1, value2, "netWorth");
            return (Criteria) this;
        }

        public Criteria andNetWorthNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("net_worth not between", value1, value2, "netWorth");
            return (Criteria) this;
        }

        public Criteria andNetWorthDateIsNull() {
            addCriterion("net_worth_date is null");
            return (Criteria) this;
        }

        public Criteria andNetWorthDateIsNotNull() {
            addCriterion("net_worth_date is not null");
            return (Criteria) this;
        }

        public Criteria andNetWorthDateEqualTo(String value) {
            addCriterion("net_worth_date =", value, "netWorthDate");
            return (Criteria) this;
        }

        public Criteria andNetWorthDateNotEqualTo(String value) {
            addCriterion("net_worth_date <>", value, "netWorthDate");
            return (Criteria) this;
        }

        public Criteria andNetWorthDateGreaterThan(String value) {
            addCriterion("net_worth_date >", value, "netWorthDate");
            return (Criteria) this;
        }

        public Criteria andNetWorthDateGreaterThanOrEqualTo(String value) {
            addCriterion("net_worth_date >=", value, "netWorthDate");
            return (Criteria) this;
        }

        public Criteria andNetWorthDateLessThan(String value) {
            addCriterion("net_worth_date <", value, "netWorthDate");
            return (Criteria) this;
        }

        public Criteria andNetWorthDateLessThanOrEqualTo(String value) {
            addCriterion("net_worth_date <=", value, "netWorthDate");
            return (Criteria) this;
        }

        public Criteria andNetWorthDateLike(String value) {
            addCriterion("net_worth_date like", value, "netWorthDate");
            return (Criteria) this;
        }

        public Criteria andNetWorthDateNotLike(String value) {
            addCriterion("net_worth_date not like", value, "netWorthDate");
            return (Criteria) this;
        }

        public Criteria andNetWorthDateIn(List<String> values) {
            addCriterion("net_worth_date in", values, "netWorthDate");
            return (Criteria) this;
        }

        public Criteria andNetWorthDateNotIn(List<String> values) {
            addCriterion("net_worth_date not in", values, "netWorthDate");
            return (Criteria) this;
        }

        public Criteria andNetWorthDateBetween(String value1, String value2) {
            addCriterion("net_worth_date between", value1, value2, "netWorthDate");
            return (Criteria) this;
        }

        public Criteria andNetWorthDateNotBetween(String value1, String value2) {
            addCriterion("net_worth_date not between", value1, value2, "netWorthDate");
            return (Criteria) this;
        }

        public Criteria andGrowRateDailyIsNull() {
            addCriterion("grow_rate_daily is null");
            return (Criteria) this;
        }

        public Criteria andGrowRateDailyIsNotNull() {
            addCriterion("grow_rate_daily is not null");
            return (Criteria) this;
        }

        public Criteria andGrowRateDailyEqualTo(BigDecimal value) {
            addCriterion("grow_rate_daily =", value, "growRateDaily");
            return (Criteria) this;
        }

        public Criteria andGrowRateDailyNotEqualTo(BigDecimal value) {
            addCriterion("grow_rate_daily <>", value, "growRateDaily");
            return (Criteria) this;
        }

        public Criteria andGrowRateDailyGreaterThan(BigDecimal value) {
            addCriterion("grow_rate_daily >", value, "growRateDaily");
            return (Criteria) this;
        }

        public Criteria andGrowRateDailyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("grow_rate_daily >=", value, "growRateDaily");
            return (Criteria) this;
        }

        public Criteria andGrowRateDailyLessThan(BigDecimal value) {
            addCriterion("grow_rate_daily <", value, "growRateDaily");
            return (Criteria) this;
        }

        public Criteria andGrowRateDailyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("grow_rate_daily <=", value, "growRateDaily");
            return (Criteria) this;
        }

        public Criteria andGrowRateDailyIn(List<BigDecimal> values) {
            addCriterion("grow_rate_daily in", values, "growRateDaily");
            return (Criteria) this;
        }

        public Criteria andGrowRateDailyNotIn(List<BigDecimal> values) {
            addCriterion("grow_rate_daily not in", values, "growRateDaily");
            return (Criteria) this;
        }

        public Criteria andGrowRateDailyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("grow_rate_daily between", value1, value2, "growRateDaily");
            return (Criteria) this;
        }

        public Criteria andGrowRateDailyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("grow_rate_daily not between", value1, value2, "growRateDaily");
            return (Criteria) this;
        }

        public Criteria andGrowRateWeeklyIsNull() {
            addCriterion("grow_rate_weekly is null");
            return (Criteria) this;
        }

        public Criteria andGrowRateWeeklyIsNotNull() {
            addCriterion("grow_rate_weekly is not null");
            return (Criteria) this;
        }

        public Criteria andGrowRateWeeklyEqualTo(BigDecimal value) {
            addCriterion("grow_rate_weekly =", value, "growRateWeekly");
            return (Criteria) this;
        }

        public Criteria andGrowRateWeeklyNotEqualTo(BigDecimal value) {
            addCriterion("grow_rate_weekly <>", value, "growRateWeekly");
            return (Criteria) this;
        }

        public Criteria andGrowRateWeeklyGreaterThan(BigDecimal value) {
            addCriterion("grow_rate_weekly >", value, "growRateWeekly");
            return (Criteria) this;
        }

        public Criteria andGrowRateWeeklyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("grow_rate_weekly >=", value, "growRateWeekly");
            return (Criteria) this;
        }

        public Criteria andGrowRateWeeklyLessThan(BigDecimal value) {
            addCriterion("grow_rate_weekly <", value, "growRateWeekly");
            return (Criteria) this;
        }

        public Criteria andGrowRateWeeklyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("grow_rate_weekly <=", value, "growRateWeekly");
            return (Criteria) this;
        }

        public Criteria andGrowRateWeeklyIn(List<BigDecimal> values) {
            addCriterion("grow_rate_weekly in", values, "growRateWeekly");
            return (Criteria) this;
        }

        public Criteria andGrowRateWeeklyNotIn(List<BigDecimal> values) {
            addCriterion("grow_rate_weekly not in", values, "growRateWeekly");
            return (Criteria) this;
        }

        public Criteria andGrowRateWeeklyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("grow_rate_weekly between", value1, value2, "growRateWeekly");
            return (Criteria) this;
        }

        public Criteria andGrowRateWeeklyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("grow_rate_weekly not between", value1, value2, "growRateWeekly");
            return (Criteria) this;
        }

        public Criteria andGrowRate1monthIsNull() {
            addCriterion("grow_rate_1month is null");
            return (Criteria) this;
        }

        public Criteria andGrowRate1monthIsNotNull() {
            addCriterion("grow_rate_1month is not null");
            return (Criteria) this;
        }

        public Criteria andGrowRate1monthEqualTo(BigDecimal value) {
            addCriterion("grow_rate_1month =", value, "growRate1month");
            return (Criteria) this;
        }

        public Criteria andGrowRate1monthNotEqualTo(BigDecimal value) {
            addCriterion("grow_rate_1month <>", value, "growRate1month");
            return (Criteria) this;
        }

        public Criteria andGrowRate1monthGreaterThan(BigDecimal value) {
            addCriterion("grow_rate_1month >", value, "growRate1month");
            return (Criteria) this;
        }

        public Criteria andGrowRate1monthGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("grow_rate_1month >=", value, "growRate1month");
            return (Criteria) this;
        }

        public Criteria andGrowRate1monthLessThan(BigDecimal value) {
            addCriterion("grow_rate_1month <", value, "growRate1month");
            return (Criteria) this;
        }

        public Criteria andGrowRate1monthLessThanOrEqualTo(BigDecimal value) {
            addCriterion("grow_rate_1month <=", value, "growRate1month");
            return (Criteria) this;
        }

        public Criteria andGrowRate1monthIn(List<BigDecimal> values) {
            addCriterion("grow_rate_1month in", values, "growRate1month");
            return (Criteria) this;
        }

        public Criteria andGrowRate1monthNotIn(List<BigDecimal> values) {
            addCriterion("grow_rate_1month not in", values, "growRate1month");
            return (Criteria) this;
        }

        public Criteria andGrowRate1monthBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("grow_rate_1month between", value1, value2, "growRate1month");
            return (Criteria) this;
        }

        public Criteria andGrowRate1monthNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("grow_rate_1month not between", value1, value2, "growRate1month");
            return (Criteria) this;
        }

        public Criteria andGrowRate3monthIsNull() {
            addCriterion("grow_rate_3month is null");
            return (Criteria) this;
        }

        public Criteria andGrowRate3monthIsNotNull() {
            addCriterion("grow_rate_3month is not null");
            return (Criteria) this;
        }

        public Criteria andGrowRate3monthEqualTo(BigDecimal value) {
            addCriterion("grow_rate_3month =", value, "growRate3month");
            return (Criteria) this;
        }

        public Criteria andGrowRate3monthNotEqualTo(BigDecimal value) {
            addCriterion("grow_rate_3month <>", value, "growRate3month");
            return (Criteria) this;
        }

        public Criteria andGrowRate3monthGreaterThan(BigDecimal value) {
            addCriterion("grow_rate_3month >", value, "growRate3month");
            return (Criteria) this;
        }

        public Criteria andGrowRate3monthGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("grow_rate_3month >=", value, "growRate3month");
            return (Criteria) this;
        }

        public Criteria andGrowRate3monthLessThan(BigDecimal value) {
            addCriterion("grow_rate_3month <", value, "growRate3month");
            return (Criteria) this;
        }

        public Criteria andGrowRate3monthLessThanOrEqualTo(BigDecimal value) {
            addCriterion("grow_rate_3month <=", value, "growRate3month");
            return (Criteria) this;
        }

        public Criteria andGrowRate3monthIn(List<BigDecimal> values) {
            addCriterion("grow_rate_3month in", values, "growRate3month");
            return (Criteria) this;
        }

        public Criteria andGrowRate3monthNotIn(List<BigDecimal> values) {
            addCriterion("grow_rate_3month not in", values, "growRate3month");
            return (Criteria) this;
        }

        public Criteria andGrowRate3monthBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("grow_rate_3month between", value1, value2, "growRate3month");
            return (Criteria) this;
        }

        public Criteria andGrowRate3monthNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("grow_rate_3month not between", value1, value2, "growRate3month");
            return (Criteria) this;
        }

        public Criteria andGrowRate6monthIsNull() {
            addCriterion("grow_rate_6month is null");
            return (Criteria) this;
        }

        public Criteria andGrowRate6monthIsNotNull() {
            addCriterion("grow_rate_6month is not null");
            return (Criteria) this;
        }

        public Criteria andGrowRate6monthEqualTo(BigDecimal value) {
            addCriterion("grow_rate_6month =", value, "growRate6month");
            return (Criteria) this;
        }

        public Criteria andGrowRate6monthNotEqualTo(BigDecimal value) {
            addCriterion("grow_rate_6month <>", value, "growRate6month");
            return (Criteria) this;
        }

        public Criteria andGrowRate6monthGreaterThan(BigDecimal value) {
            addCriterion("grow_rate_6month >", value, "growRate6month");
            return (Criteria) this;
        }

        public Criteria andGrowRate6monthGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("grow_rate_6month >=", value, "growRate6month");
            return (Criteria) this;
        }

        public Criteria andGrowRate6monthLessThan(BigDecimal value) {
            addCriterion("grow_rate_6month <", value, "growRate6month");
            return (Criteria) this;
        }

        public Criteria andGrowRate6monthLessThanOrEqualTo(BigDecimal value) {
            addCriterion("grow_rate_6month <=", value, "growRate6month");
            return (Criteria) this;
        }

        public Criteria andGrowRate6monthIn(List<BigDecimal> values) {
            addCriterion("grow_rate_6month in", values, "growRate6month");
            return (Criteria) this;
        }

        public Criteria andGrowRate6monthNotIn(List<BigDecimal> values) {
            addCriterion("grow_rate_6month not in", values, "growRate6month");
            return (Criteria) this;
        }

        public Criteria andGrowRate6monthBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("grow_rate_6month between", value1, value2, "growRate6month");
            return (Criteria) this;
        }

        public Criteria andGrowRate6monthNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("grow_rate_6month not between", value1, value2, "growRate6month");
            return (Criteria) this;
        }

        public Criteria andGrowRate1yearIsNull() {
            addCriterion("grow_rate_1year is null");
            return (Criteria) this;
        }

        public Criteria andGrowRate1yearIsNotNull() {
            addCriterion("grow_rate_1year is not null");
            return (Criteria) this;
        }

        public Criteria andGrowRate1yearEqualTo(BigDecimal value) {
            addCriterion("grow_rate_1year =", value, "growRate1year");
            return (Criteria) this;
        }

        public Criteria andGrowRate1yearNotEqualTo(BigDecimal value) {
            addCriterion("grow_rate_1year <>", value, "growRate1year");
            return (Criteria) this;
        }

        public Criteria andGrowRate1yearGreaterThan(BigDecimal value) {
            addCriterion("grow_rate_1year >", value, "growRate1year");
            return (Criteria) this;
        }

        public Criteria andGrowRate1yearGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("grow_rate_1year >=", value, "growRate1year");
            return (Criteria) this;
        }

        public Criteria andGrowRate1yearLessThan(BigDecimal value) {
            addCriterion("grow_rate_1year <", value, "growRate1year");
            return (Criteria) this;
        }

        public Criteria andGrowRate1yearLessThanOrEqualTo(BigDecimal value) {
            addCriterion("grow_rate_1year <=", value, "growRate1year");
            return (Criteria) this;
        }

        public Criteria andGrowRate1yearIn(List<BigDecimal> values) {
            addCriterion("grow_rate_1year in", values, "growRate1year");
            return (Criteria) this;
        }

        public Criteria andGrowRate1yearNotIn(List<BigDecimal> values) {
            addCriterion("grow_rate_1year not in", values, "growRate1year");
            return (Criteria) this;
        }

        public Criteria andGrowRate1yearBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("grow_rate_1year between", value1, value2, "growRate1year");
            return (Criteria) this;
        }

        public Criteria andGrowRate1yearNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("grow_rate_1year not between", value1, value2, "growRate1year");
            return (Criteria) this;
        }

        public Criteria andGrowRate2yearIsNull() {
            addCriterion("grow_rate_2year is null");
            return (Criteria) this;
        }

        public Criteria andGrowRate2yearIsNotNull() {
            addCriterion("grow_rate_2year is not null");
            return (Criteria) this;
        }

        public Criteria andGrowRate2yearEqualTo(BigDecimal value) {
            addCriterion("grow_rate_2year =", value, "growRate2year");
            return (Criteria) this;
        }

        public Criteria andGrowRate2yearNotEqualTo(BigDecimal value) {
            addCriterion("grow_rate_2year <>", value, "growRate2year");
            return (Criteria) this;
        }

        public Criteria andGrowRate2yearGreaterThan(BigDecimal value) {
            addCriterion("grow_rate_2year >", value, "growRate2year");
            return (Criteria) this;
        }

        public Criteria andGrowRate2yearGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("grow_rate_2year >=", value, "growRate2year");
            return (Criteria) this;
        }

        public Criteria andGrowRate2yearLessThan(BigDecimal value) {
            addCriterion("grow_rate_2year <", value, "growRate2year");
            return (Criteria) this;
        }

        public Criteria andGrowRate2yearLessThanOrEqualTo(BigDecimal value) {
            addCriterion("grow_rate_2year <=", value, "growRate2year");
            return (Criteria) this;
        }

        public Criteria andGrowRate2yearIn(List<BigDecimal> values) {
            addCriterion("grow_rate_2year in", values, "growRate2year");
            return (Criteria) this;
        }

        public Criteria andGrowRate2yearNotIn(List<BigDecimal> values) {
            addCriterion("grow_rate_2year not in", values, "growRate2year");
            return (Criteria) this;
        }

        public Criteria andGrowRate2yearBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("grow_rate_2year between", value1, value2, "growRate2year");
            return (Criteria) this;
        }

        public Criteria andGrowRate2yearNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("grow_rate_2year not between", value1, value2, "growRate2year");
            return (Criteria) this;
        }

        public Criteria andGrowRate3yearIsNull() {
            addCriterion("grow_rate_3year is null");
            return (Criteria) this;
        }

        public Criteria andGrowRate3yearIsNotNull() {
            addCriterion("grow_rate_3year is not null");
            return (Criteria) this;
        }

        public Criteria andGrowRate3yearEqualTo(BigDecimal value) {
            addCriterion("grow_rate_3year =", value, "growRate3year");
            return (Criteria) this;
        }

        public Criteria andGrowRate3yearNotEqualTo(BigDecimal value) {
            addCriterion("grow_rate_3year <>", value, "growRate3year");
            return (Criteria) this;
        }

        public Criteria andGrowRate3yearGreaterThan(BigDecimal value) {
            addCriterion("grow_rate_3year >", value, "growRate3year");
            return (Criteria) this;
        }

        public Criteria andGrowRate3yearGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("grow_rate_3year >=", value, "growRate3year");
            return (Criteria) this;
        }

        public Criteria andGrowRate3yearLessThan(BigDecimal value) {
            addCriterion("grow_rate_3year <", value, "growRate3year");
            return (Criteria) this;
        }

        public Criteria andGrowRate3yearLessThanOrEqualTo(BigDecimal value) {
            addCriterion("grow_rate_3year <=", value, "growRate3year");
            return (Criteria) this;
        }

        public Criteria andGrowRate3yearIn(List<BigDecimal> values) {
            addCriterion("grow_rate_3year in", values, "growRate3year");
            return (Criteria) this;
        }

        public Criteria andGrowRate3yearNotIn(List<BigDecimal> values) {
            addCriterion("grow_rate_3year not in", values, "growRate3year");
            return (Criteria) this;
        }

        public Criteria andGrowRate3yearBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("grow_rate_3year between", value1, value2, "growRate3year");
            return (Criteria) this;
        }

        public Criteria andGrowRate3yearNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("grow_rate_3year not between", value1, value2, "growRate3year");
            return (Criteria) this;
        }

        public Criteria andGrowRateThisYearIsNull() {
            addCriterion("grow_rate_this_year is null");
            return (Criteria) this;
        }

        public Criteria andGrowRateThisYearIsNotNull() {
            addCriterion("grow_rate_this_year is not null");
            return (Criteria) this;
        }

        public Criteria andGrowRateThisYearEqualTo(BigDecimal value) {
            addCriterion("grow_rate_this_year =", value, "growRateThisYear");
            return (Criteria) this;
        }

        public Criteria andGrowRateThisYearNotEqualTo(BigDecimal value) {
            addCriterion("grow_rate_this_year <>", value, "growRateThisYear");
            return (Criteria) this;
        }

        public Criteria andGrowRateThisYearGreaterThan(BigDecimal value) {
            addCriterion("grow_rate_this_year >", value, "growRateThisYear");
            return (Criteria) this;
        }

        public Criteria andGrowRateThisYearGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("grow_rate_this_year >=", value, "growRateThisYear");
            return (Criteria) this;
        }

        public Criteria andGrowRateThisYearLessThan(BigDecimal value) {
            addCriterion("grow_rate_this_year <", value, "growRateThisYear");
            return (Criteria) this;
        }

        public Criteria andGrowRateThisYearLessThanOrEqualTo(BigDecimal value) {
            addCriterion("grow_rate_this_year <=", value, "growRateThisYear");
            return (Criteria) this;
        }

        public Criteria andGrowRateThisYearIn(List<BigDecimal> values) {
            addCriterion("grow_rate_this_year in", values, "growRateThisYear");
            return (Criteria) this;
        }

        public Criteria andGrowRateThisYearNotIn(List<BigDecimal> values) {
            addCriterion("grow_rate_this_year not in", values, "growRateThisYear");
            return (Criteria) this;
        }

        public Criteria andGrowRateThisYearBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("grow_rate_this_year between", value1, value2, "growRateThisYear");
            return (Criteria) this;
        }

        public Criteria andGrowRateThisYearNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("grow_rate_this_year not between", value1, value2, "growRateThisYear");
            return (Criteria) this;
        }

        public Criteria andGrowRateFromBornIsNull() {
            addCriterion("grow_rate_from_born is null");
            return (Criteria) this;
        }

        public Criteria andGrowRateFromBornIsNotNull() {
            addCriterion("grow_rate_from_born is not null");
            return (Criteria) this;
        }

        public Criteria andGrowRateFromBornEqualTo(BigDecimal value) {
            addCriterion("grow_rate_from_born =", value, "growRateFromBorn");
            return (Criteria) this;
        }

        public Criteria andGrowRateFromBornNotEqualTo(BigDecimal value) {
            addCriterion("grow_rate_from_born <>", value, "growRateFromBorn");
            return (Criteria) this;
        }

        public Criteria andGrowRateFromBornGreaterThan(BigDecimal value) {
            addCriterion("grow_rate_from_born >", value, "growRateFromBorn");
            return (Criteria) this;
        }

        public Criteria andGrowRateFromBornGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("grow_rate_from_born >=", value, "growRateFromBorn");
            return (Criteria) this;
        }

        public Criteria andGrowRateFromBornLessThan(BigDecimal value) {
            addCriterion("grow_rate_from_born <", value, "growRateFromBorn");
            return (Criteria) this;
        }

        public Criteria andGrowRateFromBornLessThanOrEqualTo(BigDecimal value) {
            addCriterion("grow_rate_from_born <=", value, "growRateFromBorn");
            return (Criteria) this;
        }

        public Criteria andGrowRateFromBornIn(List<BigDecimal> values) {
            addCriterion("grow_rate_from_born in", values, "growRateFromBorn");
            return (Criteria) this;
        }

        public Criteria andGrowRateFromBornNotIn(List<BigDecimal> values) {
            addCriterion("grow_rate_from_born not in", values, "growRateFromBorn");
            return (Criteria) this;
        }

        public Criteria andGrowRateFromBornBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("grow_rate_from_born between", value1, value2, "growRateFromBorn");
            return (Criteria) this;
        }

        public Criteria andGrowRateFromBornNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("grow_rate_from_born not between", value1, value2, "growRateFromBorn");
            return (Criteria) this;
        }

        public Criteria andFeeRateBuyShowIsNull() {
            addCriterion("fee_rate_buy_show is null");
            return (Criteria) this;
        }

        public Criteria andFeeRateBuyShowIsNotNull() {
            addCriterion("fee_rate_buy_show is not null");
            return (Criteria) this;
        }

        public Criteria andFeeRateBuyShowEqualTo(String value) {
            addCriterion("fee_rate_buy_show =", value, "feeRateBuyShow");
            return (Criteria) this;
        }

        public Criteria andFeeRateBuyShowNotEqualTo(String value) {
            addCriterion("fee_rate_buy_show <>", value, "feeRateBuyShow");
            return (Criteria) this;
        }

        public Criteria andFeeRateBuyShowGreaterThan(String value) {
            addCriterion("fee_rate_buy_show >", value, "feeRateBuyShow");
            return (Criteria) this;
        }

        public Criteria andFeeRateBuyShowGreaterThanOrEqualTo(String value) {
            addCriterion("fee_rate_buy_show >=", value, "feeRateBuyShow");
            return (Criteria) this;
        }

        public Criteria andFeeRateBuyShowLessThan(String value) {
            addCriterion("fee_rate_buy_show <", value, "feeRateBuyShow");
            return (Criteria) this;
        }

        public Criteria andFeeRateBuyShowLessThanOrEqualTo(String value) {
            addCriterion("fee_rate_buy_show <=", value, "feeRateBuyShow");
            return (Criteria) this;
        }

        public Criteria andFeeRateBuyShowLike(String value) {
            addCriterion("fee_rate_buy_show like", value, "feeRateBuyShow");
            return (Criteria) this;
        }

        public Criteria andFeeRateBuyShowNotLike(String value) {
            addCriterion("fee_rate_buy_show not like", value, "feeRateBuyShow");
            return (Criteria) this;
        }

        public Criteria andFeeRateBuyShowIn(List<String> values) {
            addCriterion("fee_rate_buy_show in", values, "feeRateBuyShow");
            return (Criteria) this;
        }

        public Criteria andFeeRateBuyShowNotIn(List<String> values) {
            addCriterion("fee_rate_buy_show not in", values, "feeRateBuyShow");
            return (Criteria) this;
        }

        public Criteria andFeeRateBuyShowBetween(String value1, String value2) {
            addCriterion("fee_rate_buy_show between", value1, value2, "feeRateBuyShow");
            return (Criteria) this;
        }

        public Criteria andFeeRateBuyShowNotBetween(String value1, String value2) {
            addCriterion("fee_rate_buy_show not between", value1, value2, "feeRateBuyShow");
            return (Criteria) this;
        }

        public Criteria andFeeRateBuyRealIsNull() {
            addCriterion("fee_rate_buy_real is null");
            return (Criteria) this;
        }

        public Criteria andFeeRateBuyRealIsNotNull() {
            addCriterion("fee_rate_buy_real is not null");
            return (Criteria) this;
        }

        public Criteria andFeeRateBuyRealEqualTo(String value) {
            addCriterion("fee_rate_buy_real =", value, "feeRateBuyReal");
            return (Criteria) this;
        }

        public Criteria andFeeRateBuyRealNotEqualTo(String value) {
            addCriterion("fee_rate_buy_real <>", value, "feeRateBuyReal");
            return (Criteria) this;
        }

        public Criteria andFeeRateBuyRealGreaterThan(String value) {
            addCriterion("fee_rate_buy_real >", value, "feeRateBuyReal");
            return (Criteria) this;
        }

        public Criteria andFeeRateBuyRealGreaterThanOrEqualTo(String value) {
            addCriterion("fee_rate_buy_real >=", value, "feeRateBuyReal");
            return (Criteria) this;
        }

        public Criteria andFeeRateBuyRealLessThan(String value) {
            addCriterion("fee_rate_buy_real <", value, "feeRateBuyReal");
            return (Criteria) this;
        }

        public Criteria andFeeRateBuyRealLessThanOrEqualTo(String value) {
            addCriterion("fee_rate_buy_real <=", value, "feeRateBuyReal");
            return (Criteria) this;
        }

        public Criteria andFeeRateBuyRealLike(String value) {
            addCriterion("fee_rate_buy_real like", value, "feeRateBuyReal");
            return (Criteria) this;
        }

        public Criteria andFeeRateBuyRealNotLike(String value) {
            addCriterion("fee_rate_buy_real not like", value, "feeRateBuyReal");
            return (Criteria) this;
        }

        public Criteria andFeeRateBuyRealIn(List<String> values) {
            addCriterion("fee_rate_buy_real in", values, "feeRateBuyReal");
            return (Criteria) this;
        }

        public Criteria andFeeRateBuyRealNotIn(List<String> values) {
            addCriterion("fee_rate_buy_real not in", values, "feeRateBuyReal");
            return (Criteria) this;
        }

        public Criteria andFeeRateBuyRealBetween(String value1, String value2) {
            addCriterion("fee_rate_buy_real between", value1, value2, "feeRateBuyReal");
            return (Criteria) this;
        }

        public Criteria andFeeRateBuyRealNotBetween(String value1, String value2) {
            addCriterion("fee_rate_buy_real not between", value1, value2, "feeRateBuyReal");
            return (Criteria) this;
        }

        public Criteria andFeeRateRedeemIsNull() {
            addCriterion("fee_rate_redeem is null");
            return (Criteria) this;
        }

        public Criteria andFeeRateRedeemIsNotNull() {
            addCriterion("fee_rate_redeem is not null");
            return (Criteria) this;
        }

        public Criteria andFeeRateRedeemEqualTo(String value) {
            addCriterion("fee_rate_redeem =", value, "feeRateRedeem");
            return (Criteria) this;
        }

        public Criteria andFeeRateRedeemNotEqualTo(String value) {
            addCriterion("fee_rate_redeem <>", value, "feeRateRedeem");
            return (Criteria) this;
        }

        public Criteria andFeeRateRedeemGreaterThan(String value) {
            addCriterion("fee_rate_redeem >", value, "feeRateRedeem");
            return (Criteria) this;
        }

        public Criteria andFeeRateRedeemGreaterThanOrEqualTo(String value) {
            addCriterion("fee_rate_redeem >=", value, "feeRateRedeem");
            return (Criteria) this;
        }

        public Criteria andFeeRateRedeemLessThan(String value) {
            addCriterion("fee_rate_redeem <", value, "feeRateRedeem");
            return (Criteria) this;
        }

        public Criteria andFeeRateRedeemLessThanOrEqualTo(String value) {
            addCriterion("fee_rate_redeem <=", value, "feeRateRedeem");
            return (Criteria) this;
        }

        public Criteria andFeeRateRedeemLike(String value) {
            addCriterion("fee_rate_redeem like", value, "feeRateRedeem");
            return (Criteria) this;
        }

        public Criteria andFeeRateRedeemNotLike(String value) {
            addCriterion("fee_rate_redeem not like", value, "feeRateRedeem");
            return (Criteria) this;
        }

        public Criteria andFeeRateRedeemIn(List<String> values) {
            addCriterion("fee_rate_redeem in", values, "feeRateRedeem");
            return (Criteria) this;
        }

        public Criteria andFeeRateRedeemNotIn(List<String> values) {
            addCriterion("fee_rate_redeem not in", values, "feeRateRedeem");
            return (Criteria) this;
        }

        public Criteria andFeeRateRedeemBetween(String value1, String value2) {
            addCriterion("fee_rate_redeem between", value1, value2, "feeRateRedeem");
            return (Criteria) this;
        }

        public Criteria andFeeRateRedeemNotBetween(String value1, String value2) {
            addCriterion("fee_rate_redeem not between", value1, value2, "feeRateRedeem");
            return (Criteria) this;
        }

        public Criteria andMinBuyAmountIsNull() {
            addCriterion("min_buy_amount is null");
            return (Criteria) this;
        }

        public Criteria andMinBuyAmountIsNotNull() {
            addCriterion("min_buy_amount is not null");
            return (Criteria) this;
        }

        public Criteria andMinBuyAmountEqualTo(String value) {
            addCriterion("min_buy_amount =", value, "minBuyAmount");
            return (Criteria) this;
        }

        public Criteria andMinBuyAmountNotEqualTo(String value) {
            addCriterion("min_buy_amount <>", value, "minBuyAmount");
            return (Criteria) this;
        }

        public Criteria andMinBuyAmountGreaterThan(String value) {
            addCriterion("min_buy_amount >", value, "minBuyAmount");
            return (Criteria) this;
        }

        public Criteria andMinBuyAmountGreaterThanOrEqualTo(String value) {
            addCriterion("min_buy_amount >=", value, "minBuyAmount");
            return (Criteria) this;
        }

        public Criteria andMinBuyAmountLessThan(String value) {
            addCriterion("min_buy_amount <", value, "minBuyAmount");
            return (Criteria) this;
        }

        public Criteria andMinBuyAmountLessThanOrEqualTo(String value) {
            addCriterion("min_buy_amount <=", value, "minBuyAmount");
            return (Criteria) this;
        }

        public Criteria andMinBuyAmountLike(String value) {
            addCriterion("min_buy_amount like", value, "minBuyAmount");
            return (Criteria) this;
        }

        public Criteria andMinBuyAmountNotLike(String value) {
            addCriterion("min_buy_amount not like", value, "minBuyAmount");
            return (Criteria) this;
        }

        public Criteria andMinBuyAmountIn(List<String> values) {
            addCriterion("min_buy_amount in", values, "minBuyAmount");
            return (Criteria) this;
        }

        public Criteria andMinBuyAmountNotIn(List<String> values) {
            addCriterion("min_buy_amount not in", values, "minBuyAmount");
            return (Criteria) this;
        }

        public Criteria andMinBuyAmountBetween(String value1, String value2) {
            addCriterion("min_buy_amount between", value1, value2, "minBuyAmount");
            return (Criteria) this;
        }

        public Criteria andMinBuyAmountNotBetween(String value1, String value2) {
            addCriterion("min_buy_amount not between", value1, value2, "minBuyAmount");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fund_product_info
     *
     * @mbg.generated do_not_delete_during_merge Sun Oct 08 13:47:39 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fund_product_info
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}