package com.autumnsinger.dal.model;

import java.math.BigDecimal;
import java.util.Date;

public class JijinDaily {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_daily.id
     *
     * @mbg.generated Sun Oct 08 13:47:38 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_daily.searchDate
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private String searchdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_daily.productType
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private String producttype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_daily.trdVol
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private BigDecimal trdvol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_daily.trdVol1
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private BigDecimal trdvol1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_daily.trdAmt
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private BigDecimal trdamt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_daily.trdTm
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private BigDecimal trdtm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_daily.trdTm1
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private BigDecimal trdtm1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_daily.marketValue
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private BigDecimal marketvalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_daily.negotiableValue
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private BigDecimal negotiablevalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_daily.profitRate
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private BigDecimal profitrate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_daily.profitRate1
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private BigDecimal profitrate1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_daily.istVol
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private BigDecimal istvol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_daily.create_time
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_daily.update_time
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_daily.id
     *
     * @return the value of jijin_daily.id
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_daily.id
     *
     * @param id the value for jijin_daily.id
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_daily.searchDate
     *
     * @return the value of jijin_daily.searchDate
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public String getSearchdate() {
        return searchdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_daily.searchDate
     *
     * @param searchdate the value for jijin_daily.searchDate
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setSearchdate(String searchdate) {
        this.searchdate = searchdate == null ? null : searchdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_daily.productType
     *
     * @return the value of jijin_daily.productType
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public String getProducttype() {
        return producttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_daily.productType
     *
     * @param producttype the value for jijin_daily.productType
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setProducttype(String producttype) {
        this.producttype = producttype == null ? null : producttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_daily.trdVol
     *
     * @return the value of jijin_daily.trdVol
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public BigDecimal getTrdvol() {
        return trdvol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_daily.trdVol
     *
     * @param trdvol the value for jijin_daily.trdVol
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setTrdvol(BigDecimal trdvol) {
        this.trdvol = trdvol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_daily.trdVol1
     *
     * @return the value of jijin_daily.trdVol1
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public BigDecimal getTrdvol1() {
        return trdvol1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_daily.trdVol1
     *
     * @param trdvol1 the value for jijin_daily.trdVol1
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setTrdvol1(BigDecimal trdvol1) {
        this.trdvol1 = trdvol1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_daily.trdAmt
     *
     * @return the value of jijin_daily.trdAmt
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public BigDecimal getTrdamt() {
        return trdamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_daily.trdAmt
     *
     * @param trdamt the value for jijin_daily.trdAmt
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setTrdamt(BigDecimal trdamt) {
        this.trdamt = trdamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_daily.trdTm
     *
     * @return the value of jijin_daily.trdTm
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public BigDecimal getTrdtm() {
        return trdtm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_daily.trdTm
     *
     * @param trdtm the value for jijin_daily.trdTm
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setTrdtm(BigDecimal trdtm) {
        this.trdtm = trdtm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_daily.trdTm1
     *
     * @return the value of jijin_daily.trdTm1
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public BigDecimal getTrdtm1() {
        return trdtm1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_daily.trdTm1
     *
     * @param trdtm1 the value for jijin_daily.trdTm1
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setTrdtm1(BigDecimal trdtm1) {
        this.trdtm1 = trdtm1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_daily.marketValue
     *
     * @return the value of jijin_daily.marketValue
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public BigDecimal getMarketvalue() {
        return marketvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_daily.marketValue
     *
     * @param marketvalue the value for jijin_daily.marketValue
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setMarketvalue(BigDecimal marketvalue) {
        this.marketvalue = marketvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_daily.negotiableValue
     *
     * @return the value of jijin_daily.negotiableValue
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public BigDecimal getNegotiablevalue() {
        return negotiablevalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_daily.negotiableValue
     *
     * @param negotiablevalue the value for jijin_daily.negotiableValue
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setNegotiablevalue(BigDecimal negotiablevalue) {
        this.negotiablevalue = negotiablevalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_daily.profitRate
     *
     * @return the value of jijin_daily.profitRate
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public BigDecimal getProfitrate() {
        return profitrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_daily.profitRate
     *
     * @param profitrate the value for jijin_daily.profitRate
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setProfitrate(BigDecimal profitrate) {
        this.profitrate = profitrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_daily.profitRate1
     *
     * @return the value of jijin_daily.profitRate1
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public BigDecimal getProfitrate1() {
        return profitrate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_daily.profitRate1
     *
     * @param profitrate1 the value for jijin_daily.profitRate1
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setProfitrate1(BigDecimal profitrate1) {
        this.profitrate1 = profitrate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_daily.istVol
     *
     * @return the value of jijin_daily.istVol
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public BigDecimal getIstvol() {
        return istvol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_daily.istVol
     *
     * @param istvol the value for jijin_daily.istVol
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setIstvol(BigDecimal istvol) {
        this.istvol = istvol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_daily.create_time
     *
     * @return the value of jijin_daily.create_time
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_daily.create_time
     *
     * @param createTime the value for jijin_daily.create_time
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_daily.update_time
     *
     * @return the value of jijin_daily.update_time
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_daily.update_time
     *
     * @param updateTime the value for jijin_daily.update_time
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}