package com.autumnsinger.dal.model;

import java.math.BigDecimal;
import java.util.Date;

public class JijinMonthly {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_monthly.id
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_monthly.productType
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private String producttype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_monthly.inYear
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private String inyear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_monthly.month
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private String month;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_monthly.exchangeRate
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private String exchangerate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_monthly.mmarketValue
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private BigDecimal mmarketvalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_monthly.mmarketValuePre
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private BigDecimal mmarketvaluepre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_monthly.mmaxTrAmt
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private BigDecimal mmaxtramt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_monthly.mmaxTrAmtDate
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private String mmaxtramtdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_monthly.mmaxTrAmtPre
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private BigDecimal mmaxtramtpre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_monthly.mmaxTrVol
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private BigDecimal mmaxtrvol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_monthly.mmaxTrVolDate
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private String mmaxtrvoldate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_monthly.mmaxTrVolPre
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private BigDecimal mmaxtrvolpre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_monthly.mmaxhighTrn
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private BigDecimal mmaxhightrn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_monthly.mmaxhighTrnDate
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private String mmaxhightrndate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_monthly.mmaxhighTrnPre
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private BigDecimal mmaxhightrnpre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_monthly.mminLowTrn
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private BigDecimal mminlowtrn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_monthly.mminLowTrnDate
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private String mminlowtrndate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_monthly.mminLowTrnPre
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private BigDecimal mminlowtrnpre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_monthly.mminTrAmt
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private BigDecimal mmintramt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_monthly.mminTrAmtDate
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private String mmintramtdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_monthly.mminTrAmtPre
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private BigDecimal mmintramtpre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_monthly.mminTrVol
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private BigDecimal mmintrvol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_monthly.mminTrVolDate
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private String mmintrvoldate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_monthly.mminTrVolPre
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private BigDecimal mmintrvolpre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_monthly.mnegotiableValue
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private BigDecimal mnegotiablevalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_monthly.mnegotiableValuePre
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private BigDecimal mnegotiablevaluepre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_monthly.mprofitRate
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private String mprofitrate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_monthly.mprofitRatePre
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private String mprofitratepre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_monthly.mtotalAmt
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private BigDecimal mtotalamt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_monthly.mtotalAmtPre
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private BigDecimal mtotalamtpre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_monthly.mtotalTx
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private BigDecimal mtotaltx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_monthly.mtotalTxDate
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private String mtotaltxdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_monthly.mtotalTxPre
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private BigDecimal mtotaltxpre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_monthly.mtotalVol
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private BigDecimal mtotalvol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_monthly.mtotalVolPre
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private BigDecimal mtotalvolpre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_monthly.create_time
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jijin_monthly.update_time
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_monthly.id
     *
     * @return the value of jijin_monthly.id
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_monthly.id
     *
     * @param id the value for jijin_monthly.id
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_monthly.productType
     *
     * @return the value of jijin_monthly.productType
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public String getProducttype() {
        return producttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_monthly.productType
     *
     * @param producttype the value for jijin_monthly.productType
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setProducttype(String producttype) {
        this.producttype = producttype == null ? null : producttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_monthly.inYear
     *
     * @return the value of jijin_monthly.inYear
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public String getInyear() {
        return inyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_monthly.inYear
     *
     * @param inyear the value for jijin_monthly.inYear
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setInyear(String inyear) {
        this.inyear = inyear == null ? null : inyear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_monthly.month
     *
     * @return the value of jijin_monthly.month
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public String getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_monthly.month
     *
     * @param month the value for jijin_monthly.month
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setMonth(String month) {
        this.month = month == null ? null : month.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_monthly.exchangeRate
     *
     * @return the value of jijin_monthly.exchangeRate
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public String getExchangerate() {
        return exchangerate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_monthly.exchangeRate
     *
     * @param exchangerate the value for jijin_monthly.exchangeRate
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setExchangerate(String exchangerate) {
        this.exchangerate = exchangerate == null ? null : exchangerate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_monthly.mmarketValue
     *
     * @return the value of jijin_monthly.mmarketValue
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public BigDecimal getMmarketvalue() {
        return mmarketvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_monthly.mmarketValue
     *
     * @param mmarketvalue the value for jijin_monthly.mmarketValue
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setMmarketvalue(BigDecimal mmarketvalue) {
        this.mmarketvalue = mmarketvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_monthly.mmarketValuePre
     *
     * @return the value of jijin_monthly.mmarketValuePre
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public BigDecimal getMmarketvaluepre() {
        return mmarketvaluepre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_monthly.mmarketValuePre
     *
     * @param mmarketvaluepre the value for jijin_monthly.mmarketValuePre
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setMmarketvaluepre(BigDecimal mmarketvaluepre) {
        this.mmarketvaluepre = mmarketvaluepre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_monthly.mmaxTrAmt
     *
     * @return the value of jijin_monthly.mmaxTrAmt
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public BigDecimal getMmaxtramt() {
        return mmaxtramt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_monthly.mmaxTrAmt
     *
     * @param mmaxtramt the value for jijin_monthly.mmaxTrAmt
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setMmaxtramt(BigDecimal mmaxtramt) {
        this.mmaxtramt = mmaxtramt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_monthly.mmaxTrAmtDate
     *
     * @return the value of jijin_monthly.mmaxTrAmtDate
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public String getMmaxtramtdate() {
        return mmaxtramtdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_monthly.mmaxTrAmtDate
     *
     * @param mmaxtramtdate the value for jijin_monthly.mmaxTrAmtDate
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setMmaxtramtdate(String mmaxtramtdate) {
        this.mmaxtramtdate = mmaxtramtdate == null ? null : mmaxtramtdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_monthly.mmaxTrAmtPre
     *
     * @return the value of jijin_monthly.mmaxTrAmtPre
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public BigDecimal getMmaxtramtpre() {
        return mmaxtramtpre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_monthly.mmaxTrAmtPre
     *
     * @param mmaxtramtpre the value for jijin_monthly.mmaxTrAmtPre
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setMmaxtramtpre(BigDecimal mmaxtramtpre) {
        this.mmaxtramtpre = mmaxtramtpre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_monthly.mmaxTrVol
     *
     * @return the value of jijin_monthly.mmaxTrVol
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public BigDecimal getMmaxtrvol() {
        return mmaxtrvol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_monthly.mmaxTrVol
     *
     * @param mmaxtrvol the value for jijin_monthly.mmaxTrVol
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setMmaxtrvol(BigDecimal mmaxtrvol) {
        this.mmaxtrvol = mmaxtrvol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_monthly.mmaxTrVolDate
     *
     * @return the value of jijin_monthly.mmaxTrVolDate
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public String getMmaxtrvoldate() {
        return mmaxtrvoldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_monthly.mmaxTrVolDate
     *
     * @param mmaxtrvoldate the value for jijin_monthly.mmaxTrVolDate
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setMmaxtrvoldate(String mmaxtrvoldate) {
        this.mmaxtrvoldate = mmaxtrvoldate == null ? null : mmaxtrvoldate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_monthly.mmaxTrVolPre
     *
     * @return the value of jijin_monthly.mmaxTrVolPre
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public BigDecimal getMmaxtrvolpre() {
        return mmaxtrvolpre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_monthly.mmaxTrVolPre
     *
     * @param mmaxtrvolpre the value for jijin_monthly.mmaxTrVolPre
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setMmaxtrvolpre(BigDecimal mmaxtrvolpre) {
        this.mmaxtrvolpre = mmaxtrvolpre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_monthly.mmaxhighTrn
     *
     * @return the value of jijin_monthly.mmaxhighTrn
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public BigDecimal getMmaxhightrn() {
        return mmaxhightrn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_monthly.mmaxhighTrn
     *
     * @param mmaxhightrn the value for jijin_monthly.mmaxhighTrn
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setMmaxhightrn(BigDecimal mmaxhightrn) {
        this.mmaxhightrn = mmaxhightrn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_monthly.mmaxhighTrnDate
     *
     * @return the value of jijin_monthly.mmaxhighTrnDate
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public String getMmaxhightrndate() {
        return mmaxhightrndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_monthly.mmaxhighTrnDate
     *
     * @param mmaxhightrndate the value for jijin_monthly.mmaxhighTrnDate
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setMmaxhightrndate(String mmaxhightrndate) {
        this.mmaxhightrndate = mmaxhightrndate == null ? null : mmaxhightrndate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_monthly.mmaxhighTrnPre
     *
     * @return the value of jijin_monthly.mmaxhighTrnPre
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public BigDecimal getMmaxhightrnpre() {
        return mmaxhightrnpre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_monthly.mmaxhighTrnPre
     *
     * @param mmaxhightrnpre the value for jijin_monthly.mmaxhighTrnPre
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setMmaxhightrnpre(BigDecimal mmaxhightrnpre) {
        this.mmaxhightrnpre = mmaxhightrnpre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_monthly.mminLowTrn
     *
     * @return the value of jijin_monthly.mminLowTrn
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public BigDecimal getMminlowtrn() {
        return mminlowtrn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_monthly.mminLowTrn
     *
     * @param mminlowtrn the value for jijin_monthly.mminLowTrn
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setMminlowtrn(BigDecimal mminlowtrn) {
        this.mminlowtrn = mminlowtrn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_monthly.mminLowTrnDate
     *
     * @return the value of jijin_monthly.mminLowTrnDate
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public String getMminlowtrndate() {
        return mminlowtrndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_monthly.mminLowTrnDate
     *
     * @param mminlowtrndate the value for jijin_monthly.mminLowTrnDate
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setMminlowtrndate(String mminlowtrndate) {
        this.mminlowtrndate = mminlowtrndate == null ? null : mminlowtrndate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_monthly.mminLowTrnPre
     *
     * @return the value of jijin_monthly.mminLowTrnPre
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public BigDecimal getMminlowtrnpre() {
        return mminlowtrnpre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_monthly.mminLowTrnPre
     *
     * @param mminlowtrnpre the value for jijin_monthly.mminLowTrnPre
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setMminlowtrnpre(BigDecimal mminlowtrnpre) {
        this.mminlowtrnpre = mminlowtrnpre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_monthly.mminTrAmt
     *
     * @return the value of jijin_monthly.mminTrAmt
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public BigDecimal getMmintramt() {
        return mmintramt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_monthly.mminTrAmt
     *
     * @param mmintramt the value for jijin_monthly.mminTrAmt
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setMmintramt(BigDecimal mmintramt) {
        this.mmintramt = mmintramt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_monthly.mminTrAmtDate
     *
     * @return the value of jijin_monthly.mminTrAmtDate
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public String getMmintramtdate() {
        return mmintramtdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_monthly.mminTrAmtDate
     *
     * @param mmintramtdate the value for jijin_monthly.mminTrAmtDate
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setMmintramtdate(String mmintramtdate) {
        this.mmintramtdate = mmintramtdate == null ? null : mmintramtdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_monthly.mminTrAmtPre
     *
     * @return the value of jijin_monthly.mminTrAmtPre
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public BigDecimal getMmintramtpre() {
        return mmintramtpre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_monthly.mminTrAmtPre
     *
     * @param mmintramtpre the value for jijin_monthly.mminTrAmtPre
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setMmintramtpre(BigDecimal mmintramtpre) {
        this.mmintramtpre = mmintramtpre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_monthly.mminTrVol
     *
     * @return the value of jijin_monthly.mminTrVol
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public BigDecimal getMmintrvol() {
        return mmintrvol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_monthly.mminTrVol
     *
     * @param mmintrvol the value for jijin_monthly.mminTrVol
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setMmintrvol(BigDecimal mmintrvol) {
        this.mmintrvol = mmintrvol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_monthly.mminTrVolDate
     *
     * @return the value of jijin_monthly.mminTrVolDate
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public String getMmintrvoldate() {
        return mmintrvoldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_monthly.mminTrVolDate
     *
     * @param mmintrvoldate the value for jijin_monthly.mminTrVolDate
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setMmintrvoldate(String mmintrvoldate) {
        this.mmintrvoldate = mmintrvoldate == null ? null : mmintrvoldate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_monthly.mminTrVolPre
     *
     * @return the value of jijin_monthly.mminTrVolPre
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public BigDecimal getMmintrvolpre() {
        return mmintrvolpre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_monthly.mminTrVolPre
     *
     * @param mmintrvolpre the value for jijin_monthly.mminTrVolPre
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setMmintrvolpre(BigDecimal mmintrvolpre) {
        this.mmintrvolpre = mmintrvolpre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_monthly.mnegotiableValue
     *
     * @return the value of jijin_monthly.mnegotiableValue
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public BigDecimal getMnegotiablevalue() {
        return mnegotiablevalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_monthly.mnegotiableValue
     *
     * @param mnegotiablevalue the value for jijin_monthly.mnegotiableValue
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setMnegotiablevalue(BigDecimal mnegotiablevalue) {
        this.mnegotiablevalue = mnegotiablevalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_monthly.mnegotiableValuePre
     *
     * @return the value of jijin_monthly.mnegotiableValuePre
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public BigDecimal getMnegotiablevaluepre() {
        return mnegotiablevaluepre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_monthly.mnegotiableValuePre
     *
     * @param mnegotiablevaluepre the value for jijin_monthly.mnegotiableValuePre
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setMnegotiablevaluepre(BigDecimal mnegotiablevaluepre) {
        this.mnegotiablevaluepre = mnegotiablevaluepre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_monthly.mprofitRate
     *
     * @return the value of jijin_monthly.mprofitRate
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public String getMprofitrate() {
        return mprofitrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_monthly.mprofitRate
     *
     * @param mprofitrate the value for jijin_monthly.mprofitRate
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setMprofitrate(String mprofitrate) {
        this.mprofitrate = mprofitrate == null ? null : mprofitrate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_monthly.mprofitRatePre
     *
     * @return the value of jijin_monthly.mprofitRatePre
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public String getMprofitratepre() {
        return mprofitratepre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_monthly.mprofitRatePre
     *
     * @param mprofitratepre the value for jijin_monthly.mprofitRatePre
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setMprofitratepre(String mprofitratepre) {
        this.mprofitratepre = mprofitratepre == null ? null : mprofitratepre.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_monthly.mtotalAmt
     *
     * @return the value of jijin_monthly.mtotalAmt
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public BigDecimal getMtotalamt() {
        return mtotalamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_monthly.mtotalAmt
     *
     * @param mtotalamt the value for jijin_monthly.mtotalAmt
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setMtotalamt(BigDecimal mtotalamt) {
        this.mtotalamt = mtotalamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_monthly.mtotalAmtPre
     *
     * @return the value of jijin_monthly.mtotalAmtPre
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public BigDecimal getMtotalamtpre() {
        return mtotalamtpre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_monthly.mtotalAmtPre
     *
     * @param mtotalamtpre the value for jijin_monthly.mtotalAmtPre
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setMtotalamtpre(BigDecimal mtotalamtpre) {
        this.mtotalamtpre = mtotalamtpre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_monthly.mtotalTx
     *
     * @return the value of jijin_monthly.mtotalTx
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public BigDecimal getMtotaltx() {
        return mtotaltx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_monthly.mtotalTx
     *
     * @param mtotaltx the value for jijin_monthly.mtotalTx
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setMtotaltx(BigDecimal mtotaltx) {
        this.mtotaltx = mtotaltx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_monthly.mtotalTxDate
     *
     * @return the value of jijin_monthly.mtotalTxDate
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public String getMtotaltxdate() {
        return mtotaltxdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_monthly.mtotalTxDate
     *
     * @param mtotaltxdate the value for jijin_monthly.mtotalTxDate
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setMtotaltxdate(String mtotaltxdate) {
        this.mtotaltxdate = mtotaltxdate == null ? null : mtotaltxdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_monthly.mtotalTxPre
     *
     * @return the value of jijin_monthly.mtotalTxPre
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public BigDecimal getMtotaltxpre() {
        return mtotaltxpre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_monthly.mtotalTxPre
     *
     * @param mtotaltxpre the value for jijin_monthly.mtotalTxPre
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setMtotaltxpre(BigDecimal mtotaltxpre) {
        this.mtotaltxpre = mtotaltxpre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_monthly.mtotalVol
     *
     * @return the value of jijin_monthly.mtotalVol
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public BigDecimal getMtotalvol() {
        return mtotalvol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_monthly.mtotalVol
     *
     * @param mtotalvol the value for jijin_monthly.mtotalVol
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setMtotalvol(BigDecimal mtotalvol) {
        this.mtotalvol = mtotalvol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_monthly.mtotalVolPre
     *
     * @return the value of jijin_monthly.mtotalVolPre
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public BigDecimal getMtotalvolpre() {
        return mtotalvolpre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_monthly.mtotalVolPre
     *
     * @param mtotalvolpre the value for jijin_monthly.mtotalVolPre
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setMtotalvolpre(BigDecimal mtotalvolpre) {
        this.mtotalvolpre = mtotalvolpre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_monthly.create_time
     *
     * @return the value of jijin_monthly.create_time
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_monthly.create_time
     *
     * @param createTime the value for jijin_monthly.create_time
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jijin_monthly.update_time
     *
     * @return the value of jijin_monthly.update_time
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jijin_monthly.update_time
     *
     * @param updateTime the value for jijin_monthly.update_time
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}