package com.autumnsinger.dal.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class JijinMonthlyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jijin_monthly
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jijin_monthly
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jijin_monthly
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    protected List<Criteria> oredCriteria;

    private Integer limit;

    private Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jijin_monthly
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public JijinMonthlyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jijin_monthly
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jijin_monthly
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jijin_monthly
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jijin_monthly
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jijin_monthly
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jijin_monthly
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jijin_monthly
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jijin_monthly
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jijin_monthly
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jijin_monthly
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jijin_monthly
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProducttypeIsNull() {
            addCriterion("productType is null");
            return (Criteria) this;
        }

        public Criteria andProducttypeIsNotNull() {
            addCriterion("productType is not null");
            return (Criteria) this;
        }

        public Criteria andProducttypeEqualTo(String value) {
            addCriterion("productType =", value, "producttype");
            return (Criteria) this;
        }

        public Criteria andProducttypeNotEqualTo(String value) {
            addCriterion("productType <>", value, "producttype");
            return (Criteria) this;
        }

        public Criteria andProducttypeGreaterThan(String value) {
            addCriterion("productType >", value, "producttype");
            return (Criteria) this;
        }

        public Criteria andProducttypeGreaterThanOrEqualTo(String value) {
            addCriterion("productType >=", value, "producttype");
            return (Criteria) this;
        }

        public Criteria andProducttypeLessThan(String value) {
            addCriterion("productType <", value, "producttype");
            return (Criteria) this;
        }

        public Criteria andProducttypeLessThanOrEqualTo(String value) {
            addCriterion("productType <=", value, "producttype");
            return (Criteria) this;
        }

        public Criteria andProducttypeLike(String value) {
            addCriterion("productType like", value, "producttype");
            return (Criteria) this;
        }

        public Criteria andProducttypeNotLike(String value) {
            addCriterion("productType not like", value, "producttype");
            return (Criteria) this;
        }

        public Criteria andProducttypeIn(List<String> values) {
            addCriterion("productType in", values, "producttype");
            return (Criteria) this;
        }

        public Criteria andProducttypeNotIn(List<String> values) {
            addCriterion("productType not in", values, "producttype");
            return (Criteria) this;
        }

        public Criteria andProducttypeBetween(String value1, String value2) {
            addCriterion("productType between", value1, value2, "producttype");
            return (Criteria) this;
        }

        public Criteria andProducttypeNotBetween(String value1, String value2) {
            addCriterion("productType not between", value1, value2, "producttype");
            return (Criteria) this;
        }

        public Criteria andInyearIsNull() {
            addCriterion("inYear is null");
            return (Criteria) this;
        }

        public Criteria andInyearIsNotNull() {
            addCriterion("inYear is not null");
            return (Criteria) this;
        }

        public Criteria andInyearEqualTo(String value) {
            addCriterion("inYear =", value, "inyear");
            return (Criteria) this;
        }

        public Criteria andInyearNotEqualTo(String value) {
            addCriterion("inYear <>", value, "inyear");
            return (Criteria) this;
        }

        public Criteria andInyearGreaterThan(String value) {
            addCriterion("inYear >", value, "inyear");
            return (Criteria) this;
        }

        public Criteria andInyearGreaterThanOrEqualTo(String value) {
            addCriterion("inYear >=", value, "inyear");
            return (Criteria) this;
        }

        public Criteria andInyearLessThan(String value) {
            addCriterion("inYear <", value, "inyear");
            return (Criteria) this;
        }

        public Criteria andInyearLessThanOrEqualTo(String value) {
            addCriterion("inYear <=", value, "inyear");
            return (Criteria) this;
        }

        public Criteria andInyearLike(String value) {
            addCriterion("inYear like", value, "inyear");
            return (Criteria) this;
        }

        public Criteria andInyearNotLike(String value) {
            addCriterion("inYear not like", value, "inyear");
            return (Criteria) this;
        }

        public Criteria andInyearIn(List<String> values) {
            addCriterion("inYear in", values, "inyear");
            return (Criteria) this;
        }

        public Criteria andInyearNotIn(List<String> values) {
            addCriterion("inYear not in", values, "inyear");
            return (Criteria) this;
        }

        public Criteria andInyearBetween(String value1, String value2) {
            addCriterion("inYear between", value1, value2, "inyear");
            return (Criteria) this;
        }

        public Criteria andInyearNotBetween(String value1, String value2) {
            addCriterion("inYear not between", value1, value2, "inyear");
            return (Criteria) this;
        }

        public Criteria andMonthIsNull() {
            addCriterion("month is null");
            return (Criteria) this;
        }

        public Criteria andMonthIsNotNull() {
            addCriterion("month is not null");
            return (Criteria) this;
        }

        public Criteria andMonthEqualTo(String value) {
            addCriterion("month =", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthNotEqualTo(String value) {
            addCriterion("month <>", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthGreaterThan(String value) {
            addCriterion("month >", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthGreaterThanOrEqualTo(String value) {
            addCriterion("month >=", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthLessThan(String value) {
            addCriterion("month <", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthLessThanOrEqualTo(String value) {
            addCriterion("month <=", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthLike(String value) {
            addCriterion("month like", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthNotLike(String value) {
            addCriterion("month not like", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthIn(List<String> values) {
            addCriterion("month in", values, "month");
            return (Criteria) this;
        }

        public Criteria andMonthNotIn(List<String> values) {
            addCriterion("month not in", values, "month");
            return (Criteria) this;
        }

        public Criteria andMonthBetween(String value1, String value2) {
            addCriterion("month between", value1, value2, "month");
            return (Criteria) this;
        }

        public Criteria andMonthNotBetween(String value1, String value2) {
            addCriterion("month not between", value1, value2, "month");
            return (Criteria) this;
        }

        public Criteria andExchangerateIsNull() {
            addCriterion("exchangeRate is null");
            return (Criteria) this;
        }

        public Criteria andExchangerateIsNotNull() {
            addCriterion("exchangeRate is not null");
            return (Criteria) this;
        }

        public Criteria andExchangerateEqualTo(String value) {
            addCriterion("exchangeRate =", value, "exchangerate");
            return (Criteria) this;
        }

        public Criteria andExchangerateNotEqualTo(String value) {
            addCriterion("exchangeRate <>", value, "exchangerate");
            return (Criteria) this;
        }

        public Criteria andExchangerateGreaterThan(String value) {
            addCriterion("exchangeRate >", value, "exchangerate");
            return (Criteria) this;
        }

        public Criteria andExchangerateGreaterThanOrEqualTo(String value) {
            addCriterion("exchangeRate >=", value, "exchangerate");
            return (Criteria) this;
        }

        public Criteria andExchangerateLessThan(String value) {
            addCriterion("exchangeRate <", value, "exchangerate");
            return (Criteria) this;
        }

        public Criteria andExchangerateLessThanOrEqualTo(String value) {
            addCriterion("exchangeRate <=", value, "exchangerate");
            return (Criteria) this;
        }

        public Criteria andExchangerateLike(String value) {
            addCriterion("exchangeRate like", value, "exchangerate");
            return (Criteria) this;
        }

        public Criteria andExchangerateNotLike(String value) {
            addCriterion("exchangeRate not like", value, "exchangerate");
            return (Criteria) this;
        }

        public Criteria andExchangerateIn(List<String> values) {
            addCriterion("exchangeRate in", values, "exchangerate");
            return (Criteria) this;
        }

        public Criteria andExchangerateNotIn(List<String> values) {
            addCriterion("exchangeRate not in", values, "exchangerate");
            return (Criteria) this;
        }

        public Criteria andExchangerateBetween(String value1, String value2) {
            addCriterion("exchangeRate between", value1, value2, "exchangerate");
            return (Criteria) this;
        }

        public Criteria andExchangerateNotBetween(String value1, String value2) {
            addCriterion("exchangeRate not between", value1, value2, "exchangerate");
            return (Criteria) this;
        }

        public Criteria andMmarketvalueIsNull() {
            addCriterion("mmarketValue is null");
            return (Criteria) this;
        }

        public Criteria andMmarketvalueIsNotNull() {
            addCriterion("mmarketValue is not null");
            return (Criteria) this;
        }

        public Criteria andMmarketvalueEqualTo(BigDecimal value) {
            addCriterion("mmarketValue =", value, "mmarketvalue");
            return (Criteria) this;
        }

        public Criteria andMmarketvalueNotEqualTo(BigDecimal value) {
            addCriterion("mmarketValue <>", value, "mmarketvalue");
            return (Criteria) this;
        }

        public Criteria andMmarketvalueGreaterThan(BigDecimal value) {
            addCriterion("mmarketValue >", value, "mmarketvalue");
            return (Criteria) this;
        }

        public Criteria andMmarketvalueGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("mmarketValue >=", value, "mmarketvalue");
            return (Criteria) this;
        }

        public Criteria andMmarketvalueLessThan(BigDecimal value) {
            addCriterion("mmarketValue <", value, "mmarketvalue");
            return (Criteria) this;
        }

        public Criteria andMmarketvalueLessThanOrEqualTo(BigDecimal value) {
            addCriterion("mmarketValue <=", value, "mmarketvalue");
            return (Criteria) this;
        }

        public Criteria andMmarketvalueIn(List<BigDecimal> values) {
            addCriterion("mmarketValue in", values, "mmarketvalue");
            return (Criteria) this;
        }

        public Criteria andMmarketvalueNotIn(List<BigDecimal> values) {
            addCriterion("mmarketValue not in", values, "mmarketvalue");
            return (Criteria) this;
        }

        public Criteria andMmarketvalueBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mmarketValue between", value1, value2, "mmarketvalue");
            return (Criteria) this;
        }

        public Criteria andMmarketvalueNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mmarketValue not between", value1, value2, "mmarketvalue");
            return (Criteria) this;
        }

        public Criteria andMmarketvaluepreIsNull() {
            addCriterion("mmarketValuePre is null");
            return (Criteria) this;
        }

        public Criteria andMmarketvaluepreIsNotNull() {
            addCriterion("mmarketValuePre is not null");
            return (Criteria) this;
        }

        public Criteria andMmarketvaluepreEqualTo(BigDecimal value) {
            addCriterion("mmarketValuePre =", value, "mmarketvaluepre");
            return (Criteria) this;
        }

        public Criteria andMmarketvaluepreNotEqualTo(BigDecimal value) {
            addCriterion("mmarketValuePre <>", value, "mmarketvaluepre");
            return (Criteria) this;
        }

        public Criteria andMmarketvaluepreGreaterThan(BigDecimal value) {
            addCriterion("mmarketValuePre >", value, "mmarketvaluepre");
            return (Criteria) this;
        }

        public Criteria andMmarketvaluepreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("mmarketValuePre >=", value, "mmarketvaluepre");
            return (Criteria) this;
        }

        public Criteria andMmarketvaluepreLessThan(BigDecimal value) {
            addCriterion("mmarketValuePre <", value, "mmarketvaluepre");
            return (Criteria) this;
        }

        public Criteria andMmarketvaluepreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("mmarketValuePre <=", value, "mmarketvaluepre");
            return (Criteria) this;
        }

        public Criteria andMmarketvaluepreIn(List<BigDecimal> values) {
            addCriterion("mmarketValuePre in", values, "mmarketvaluepre");
            return (Criteria) this;
        }

        public Criteria andMmarketvaluepreNotIn(List<BigDecimal> values) {
            addCriterion("mmarketValuePre not in", values, "mmarketvaluepre");
            return (Criteria) this;
        }

        public Criteria andMmarketvaluepreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mmarketValuePre between", value1, value2, "mmarketvaluepre");
            return (Criteria) this;
        }

        public Criteria andMmarketvaluepreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mmarketValuePre not between", value1, value2, "mmarketvaluepre");
            return (Criteria) this;
        }

        public Criteria andMmaxtramtIsNull() {
            addCriterion("mmaxTrAmt is null");
            return (Criteria) this;
        }

        public Criteria andMmaxtramtIsNotNull() {
            addCriterion("mmaxTrAmt is not null");
            return (Criteria) this;
        }

        public Criteria andMmaxtramtEqualTo(BigDecimal value) {
            addCriterion("mmaxTrAmt =", value, "mmaxtramt");
            return (Criteria) this;
        }

        public Criteria andMmaxtramtNotEqualTo(BigDecimal value) {
            addCriterion("mmaxTrAmt <>", value, "mmaxtramt");
            return (Criteria) this;
        }

        public Criteria andMmaxtramtGreaterThan(BigDecimal value) {
            addCriterion("mmaxTrAmt >", value, "mmaxtramt");
            return (Criteria) this;
        }

        public Criteria andMmaxtramtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("mmaxTrAmt >=", value, "mmaxtramt");
            return (Criteria) this;
        }

        public Criteria andMmaxtramtLessThan(BigDecimal value) {
            addCriterion("mmaxTrAmt <", value, "mmaxtramt");
            return (Criteria) this;
        }

        public Criteria andMmaxtramtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("mmaxTrAmt <=", value, "mmaxtramt");
            return (Criteria) this;
        }

        public Criteria andMmaxtramtIn(List<BigDecimal> values) {
            addCriterion("mmaxTrAmt in", values, "mmaxtramt");
            return (Criteria) this;
        }

        public Criteria andMmaxtramtNotIn(List<BigDecimal> values) {
            addCriterion("mmaxTrAmt not in", values, "mmaxtramt");
            return (Criteria) this;
        }

        public Criteria andMmaxtramtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mmaxTrAmt between", value1, value2, "mmaxtramt");
            return (Criteria) this;
        }

        public Criteria andMmaxtramtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mmaxTrAmt not between", value1, value2, "mmaxtramt");
            return (Criteria) this;
        }

        public Criteria andMmaxtramtdateIsNull() {
            addCriterion("mmaxTrAmtDate is null");
            return (Criteria) this;
        }

        public Criteria andMmaxtramtdateIsNotNull() {
            addCriterion("mmaxTrAmtDate is not null");
            return (Criteria) this;
        }

        public Criteria andMmaxtramtdateEqualTo(String value) {
            addCriterion("mmaxTrAmtDate =", value, "mmaxtramtdate");
            return (Criteria) this;
        }

        public Criteria andMmaxtramtdateNotEqualTo(String value) {
            addCriterion("mmaxTrAmtDate <>", value, "mmaxtramtdate");
            return (Criteria) this;
        }

        public Criteria andMmaxtramtdateGreaterThan(String value) {
            addCriterion("mmaxTrAmtDate >", value, "mmaxtramtdate");
            return (Criteria) this;
        }

        public Criteria andMmaxtramtdateGreaterThanOrEqualTo(String value) {
            addCriterion("mmaxTrAmtDate >=", value, "mmaxtramtdate");
            return (Criteria) this;
        }

        public Criteria andMmaxtramtdateLessThan(String value) {
            addCriterion("mmaxTrAmtDate <", value, "mmaxtramtdate");
            return (Criteria) this;
        }

        public Criteria andMmaxtramtdateLessThanOrEqualTo(String value) {
            addCriterion("mmaxTrAmtDate <=", value, "mmaxtramtdate");
            return (Criteria) this;
        }

        public Criteria andMmaxtramtdateLike(String value) {
            addCriterion("mmaxTrAmtDate like", value, "mmaxtramtdate");
            return (Criteria) this;
        }

        public Criteria andMmaxtramtdateNotLike(String value) {
            addCriterion("mmaxTrAmtDate not like", value, "mmaxtramtdate");
            return (Criteria) this;
        }

        public Criteria andMmaxtramtdateIn(List<String> values) {
            addCriterion("mmaxTrAmtDate in", values, "mmaxtramtdate");
            return (Criteria) this;
        }

        public Criteria andMmaxtramtdateNotIn(List<String> values) {
            addCriterion("mmaxTrAmtDate not in", values, "mmaxtramtdate");
            return (Criteria) this;
        }

        public Criteria andMmaxtramtdateBetween(String value1, String value2) {
            addCriterion("mmaxTrAmtDate between", value1, value2, "mmaxtramtdate");
            return (Criteria) this;
        }

        public Criteria andMmaxtramtdateNotBetween(String value1, String value2) {
            addCriterion("mmaxTrAmtDate not between", value1, value2, "mmaxtramtdate");
            return (Criteria) this;
        }

        public Criteria andMmaxtramtpreIsNull() {
            addCriterion("mmaxTrAmtPre is null");
            return (Criteria) this;
        }

        public Criteria andMmaxtramtpreIsNotNull() {
            addCriterion("mmaxTrAmtPre is not null");
            return (Criteria) this;
        }

        public Criteria andMmaxtramtpreEqualTo(BigDecimal value) {
            addCriterion("mmaxTrAmtPre =", value, "mmaxtramtpre");
            return (Criteria) this;
        }

        public Criteria andMmaxtramtpreNotEqualTo(BigDecimal value) {
            addCriterion("mmaxTrAmtPre <>", value, "mmaxtramtpre");
            return (Criteria) this;
        }

        public Criteria andMmaxtramtpreGreaterThan(BigDecimal value) {
            addCriterion("mmaxTrAmtPre >", value, "mmaxtramtpre");
            return (Criteria) this;
        }

        public Criteria andMmaxtramtpreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("mmaxTrAmtPre >=", value, "mmaxtramtpre");
            return (Criteria) this;
        }

        public Criteria andMmaxtramtpreLessThan(BigDecimal value) {
            addCriterion("mmaxTrAmtPre <", value, "mmaxtramtpre");
            return (Criteria) this;
        }

        public Criteria andMmaxtramtpreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("mmaxTrAmtPre <=", value, "mmaxtramtpre");
            return (Criteria) this;
        }

        public Criteria andMmaxtramtpreIn(List<BigDecimal> values) {
            addCriterion("mmaxTrAmtPre in", values, "mmaxtramtpre");
            return (Criteria) this;
        }

        public Criteria andMmaxtramtpreNotIn(List<BigDecimal> values) {
            addCriterion("mmaxTrAmtPre not in", values, "mmaxtramtpre");
            return (Criteria) this;
        }

        public Criteria andMmaxtramtpreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mmaxTrAmtPre between", value1, value2, "mmaxtramtpre");
            return (Criteria) this;
        }

        public Criteria andMmaxtramtpreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mmaxTrAmtPre not between", value1, value2, "mmaxtramtpre");
            return (Criteria) this;
        }

        public Criteria andMmaxtrvolIsNull() {
            addCriterion("mmaxTrVol is null");
            return (Criteria) this;
        }

        public Criteria andMmaxtrvolIsNotNull() {
            addCriterion("mmaxTrVol is not null");
            return (Criteria) this;
        }

        public Criteria andMmaxtrvolEqualTo(BigDecimal value) {
            addCriterion("mmaxTrVol =", value, "mmaxtrvol");
            return (Criteria) this;
        }

        public Criteria andMmaxtrvolNotEqualTo(BigDecimal value) {
            addCriterion("mmaxTrVol <>", value, "mmaxtrvol");
            return (Criteria) this;
        }

        public Criteria andMmaxtrvolGreaterThan(BigDecimal value) {
            addCriterion("mmaxTrVol >", value, "mmaxtrvol");
            return (Criteria) this;
        }

        public Criteria andMmaxtrvolGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("mmaxTrVol >=", value, "mmaxtrvol");
            return (Criteria) this;
        }

        public Criteria andMmaxtrvolLessThan(BigDecimal value) {
            addCriterion("mmaxTrVol <", value, "mmaxtrvol");
            return (Criteria) this;
        }

        public Criteria andMmaxtrvolLessThanOrEqualTo(BigDecimal value) {
            addCriterion("mmaxTrVol <=", value, "mmaxtrvol");
            return (Criteria) this;
        }

        public Criteria andMmaxtrvolIn(List<BigDecimal> values) {
            addCriterion("mmaxTrVol in", values, "mmaxtrvol");
            return (Criteria) this;
        }

        public Criteria andMmaxtrvolNotIn(List<BigDecimal> values) {
            addCriterion("mmaxTrVol not in", values, "mmaxtrvol");
            return (Criteria) this;
        }

        public Criteria andMmaxtrvolBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mmaxTrVol between", value1, value2, "mmaxtrvol");
            return (Criteria) this;
        }

        public Criteria andMmaxtrvolNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mmaxTrVol not between", value1, value2, "mmaxtrvol");
            return (Criteria) this;
        }

        public Criteria andMmaxtrvoldateIsNull() {
            addCriterion("mmaxTrVolDate is null");
            return (Criteria) this;
        }

        public Criteria andMmaxtrvoldateIsNotNull() {
            addCriterion("mmaxTrVolDate is not null");
            return (Criteria) this;
        }

        public Criteria andMmaxtrvoldateEqualTo(String value) {
            addCriterion("mmaxTrVolDate =", value, "mmaxtrvoldate");
            return (Criteria) this;
        }

        public Criteria andMmaxtrvoldateNotEqualTo(String value) {
            addCriterion("mmaxTrVolDate <>", value, "mmaxtrvoldate");
            return (Criteria) this;
        }

        public Criteria andMmaxtrvoldateGreaterThan(String value) {
            addCriterion("mmaxTrVolDate >", value, "mmaxtrvoldate");
            return (Criteria) this;
        }

        public Criteria andMmaxtrvoldateGreaterThanOrEqualTo(String value) {
            addCriterion("mmaxTrVolDate >=", value, "mmaxtrvoldate");
            return (Criteria) this;
        }

        public Criteria andMmaxtrvoldateLessThan(String value) {
            addCriterion("mmaxTrVolDate <", value, "mmaxtrvoldate");
            return (Criteria) this;
        }

        public Criteria andMmaxtrvoldateLessThanOrEqualTo(String value) {
            addCriterion("mmaxTrVolDate <=", value, "mmaxtrvoldate");
            return (Criteria) this;
        }

        public Criteria andMmaxtrvoldateLike(String value) {
            addCriterion("mmaxTrVolDate like", value, "mmaxtrvoldate");
            return (Criteria) this;
        }

        public Criteria andMmaxtrvoldateNotLike(String value) {
            addCriterion("mmaxTrVolDate not like", value, "mmaxtrvoldate");
            return (Criteria) this;
        }

        public Criteria andMmaxtrvoldateIn(List<String> values) {
            addCriterion("mmaxTrVolDate in", values, "mmaxtrvoldate");
            return (Criteria) this;
        }

        public Criteria andMmaxtrvoldateNotIn(List<String> values) {
            addCriterion("mmaxTrVolDate not in", values, "mmaxtrvoldate");
            return (Criteria) this;
        }

        public Criteria andMmaxtrvoldateBetween(String value1, String value2) {
            addCriterion("mmaxTrVolDate between", value1, value2, "mmaxtrvoldate");
            return (Criteria) this;
        }

        public Criteria andMmaxtrvoldateNotBetween(String value1, String value2) {
            addCriterion("mmaxTrVolDate not between", value1, value2, "mmaxtrvoldate");
            return (Criteria) this;
        }

        public Criteria andMmaxtrvolpreIsNull() {
            addCriterion("mmaxTrVolPre is null");
            return (Criteria) this;
        }

        public Criteria andMmaxtrvolpreIsNotNull() {
            addCriterion("mmaxTrVolPre is not null");
            return (Criteria) this;
        }

        public Criteria andMmaxtrvolpreEqualTo(BigDecimal value) {
            addCriterion("mmaxTrVolPre =", value, "mmaxtrvolpre");
            return (Criteria) this;
        }

        public Criteria andMmaxtrvolpreNotEqualTo(BigDecimal value) {
            addCriterion("mmaxTrVolPre <>", value, "mmaxtrvolpre");
            return (Criteria) this;
        }

        public Criteria andMmaxtrvolpreGreaterThan(BigDecimal value) {
            addCriterion("mmaxTrVolPre >", value, "mmaxtrvolpre");
            return (Criteria) this;
        }

        public Criteria andMmaxtrvolpreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("mmaxTrVolPre >=", value, "mmaxtrvolpre");
            return (Criteria) this;
        }

        public Criteria andMmaxtrvolpreLessThan(BigDecimal value) {
            addCriterion("mmaxTrVolPre <", value, "mmaxtrvolpre");
            return (Criteria) this;
        }

        public Criteria andMmaxtrvolpreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("mmaxTrVolPre <=", value, "mmaxtrvolpre");
            return (Criteria) this;
        }

        public Criteria andMmaxtrvolpreIn(List<BigDecimal> values) {
            addCriterion("mmaxTrVolPre in", values, "mmaxtrvolpre");
            return (Criteria) this;
        }

        public Criteria andMmaxtrvolpreNotIn(List<BigDecimal> values) {
            addCriterion("mmaxTrVolPre not in", values, "mmaxtrvolpre");
            return (Criteria) this;
        }

        public Criteria andMmaxtrvolpreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mmaxTrVolPre between", value1, value2, "mmaxtrvolpre");
            return (Criteria) this;
        }

        public Criteria andMmaxtrvolpreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mmaxTrVolPre not between", value1, value2, "mmaxtrvolpre");
            return (Criteria) this;
        }

        public Criteria andMmaxhightrnIsNull() {
            addCriterion("mmaxhighTrn is null");
            return (Criteria) this;
        }

        public Criteria andMmaxhightrnIsNotNull() {
            addCriterion("mmaxhighTrn is not null");
            return (Criteria) this;
        }

        public Criteria andMmaxhightrnEqualTo(BigDecimal value) {
            addCriterion("mmaxhighTrn =", value, "mmaxhightrn");
            return (Criteria) this;
        }

        public Criteria andMmaxhightrnNotEqualTo(BigDecimal value) {
            addCriterion("mmaxhighTrn <>", value, "mmaxhightrn");
            return (Criteria) this;
        }

        public Criteria andMmaxhightrnGreaterThan(BigDecimal value) {
            addCriterion("mmaxhighTrn >", value, "mmaxhightrn");
            return (Criteria) this;
        }

        public Criteria andMmaxhightrnGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("mmaxhighTrn >=", value, "mmaxhightrn");
            return (Criteria) this;
        }

        public Criteria andMmaxhightrnLessThan(BigDecimal value) {
            addCriterion("mmaxhighTrn <", value, "mmaxhightrn");
            return (Criteria) this;
        }

        public Criteria andMmaxhightrnLessThanOrEqualTo(BigDecimal value) {
            addCriterion("mmaxhighTrn <=", value, "mmaxhightrn");
            return (Criteria) this;
        }

        public Criteria andMmaxhightrnIn(List<BigDecimal> values) {
            addCriterion("mmaxhighTrn in", values, "mmaxhightrn");
            return (Criteria) this;
        }

        public Criteria andMmaxhightrnNotIn(List<BigDecimal> values) {
            addCriterion("mmaxhighTrn not in", values, "mmaxhightrn");
            return (Criteria) this;
        }

        public Criteria andMmaxhightrnBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mmaxhighTrn between", value1, value2, "mmaxhightrn");
            return (Criteria) this;
        }

        public Criteria andMmaxhightrnNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mmaxhighTrn not between", value1, value2, "mmaxhightrn");
            return (Criteria) this;
        }

        public Criteria andMmaxhightrndateIsNull() {
            addCriterion("mmaxhighTrnDate is null");
            return (Criteria) this;
        }

        public Criteria andMmaxhightrndateIsNotNull() {
            addCriterion("mmaxhighTrnDate is not null");
            return (Criteria) this;
        }

        public Criteria andMmaxhightrndateEqualTo(String value) {
            addCriterion("mmaxhighTrnDate =", value, "mmaxhightrndate");
            return (Criteria) this;
        }

        public Criteria andMmaxhightrndateNotEqualTo(String value) {
            addCriterion("mmaxhighTrnDate <>", value, "mmaxhightrndate");
            return (Criteria) this;
        }

        public Criteria andMmaxhightrndateGreaterThan(String value) {
            addCriterion("mmaxhighTrnDate >", value, "mmaxhightrndate");
            return (Criteria) this;
        }

        public Criteria andMmaxhightrndateGreaterThanOrEqualTo(String value) {
            addCriterion("mmaxhighTrnDate >=", value, "mmaxhightrndate");
            return (Criteria) this;
        }

        public Criteria andMmaxhightrndateLessThan(String value) {
            addCriterion("mmaxhighTrnDate <", value, "mmaxhightrndate");
            return (Criteria) this;
        }

        public Criteria andMmaxhightrndateLessThanOrEqualTo(String value) {
            addCriterion("mmaxhighTrnDate <=", value, "mmaxhightrndate");
            return (Criteria) this;
        }

        public Criteria andMmaxhightrndateLike(String value) {
            addCriterion("mmaxhighTrnDate like", value, "mmaxhightrndate");
            return (Criteria) this;
        }

        public Criteria andMmaxhightrndateNotLike(String value) {
            addCriterion("mmaxhighTrnDate not like", value, "mmaxhightrndate");
            return (Criteria) this;
        }

        public Criteria andMmaxhightrndateIn(List<String> values) {
            addCriterion("mmaxhighTrnDate in", values, "mmaxhightrndate");
            return (Criteria) this;
        }

        public Criteria andMmaxhightrndateNotIn(List<String> values) {
            addCriterion("mmaxhighTrnDate not in", values, "mmaxhightrndate");
            return (Criteria) this;
        }

        public Criteria andMmaxhightrndateBetween(String value1, String value2) {
            addCriterion("mmaxhighTrnDate between", value1, value2, "mmaxhightrndate");
            return (Criteria) this;
        }

        public Criteria andMmaxhightrndateNotBetween(String value1, String value2) {
            addCriterion("mmaxhighTrnDate not between", value1, value2, "mmaxhightrndate");
            return (Criteria) this;
        }

        public Criteria andMmaxhightrnpreIsNull() {
            addCriterion("mmaxhighTrnPre is null");
            return (Criteria) this;
        }

        public Criteria andMmaxhightrnpreIsNotNull() {
            addCriterion("mmaxhighTrnPre is not null");
            return (Criteria) this;
        }

        public Criteria andMmaxhightrnpreEqualTo(BigDecimal value) {
            addCriterion("mmaxhighTrnPre =", value, "mmaxhightrnpre");
            return (Criteria) this;
        }

        public Criteria andMmaxhightrnpreNotEqualTo(BigDecimal value) {
            addCriterion("mmaxhighTrnPre <>", value, "mmaxhightrnpre");
            return (Criteria) this;
        }

        public Criteria andMmaxhightrnpreGreaterThan(BigDecimal value) {
            addCriterion("mmaxhighTrnPre >", value, "mmaxhightrnpre");
            return (Criteria) this;
        }

        public Criteria andMmaxhightrnpreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("mmaxhighTrnPre >=", value, "mmaxhightrnpre");
            return (Criteria) this;
        }

        public Criteria andMmaxhightrnpreLessThan(BigDecimal value) {
            addCriterion("mmaxhighTrnPre <", value, "mmaxhightrnpre");
            return (Criteria) this;
        }

        public Criteria andMmaxhightrnpreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("mmaxhighTrnPre <=", value, "mmaxhightrnpre");
            return (Criteria) this;
        }

        public Criteria andMmaxhightrnpreIn(List<BigDecimal> values) {
            addCriterion("mmaxhighTrnPre in", values, "mmaxhightrnpre");
            return (Criteria) this;
        }

        public Criteria andMmaxhightrnpreNotIn(List<BigDecimal> values) {
            addCriterion("mmaxhighTrnPre not in", values, "mmaxhightrnpre");
            return (Criteria) this;
        }

        public Criteria andMmaxhightrnpreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mmaxhighTrnPre between", value1, value2, "mmaxhightrnpre");
            return (Criteria) this;
        }

        public Criteria andMmaxhightrnpreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mmaxhighTrnPre not between", value1, value2, "mmaxhightrnpre");
            return (Criteria) this;
        }

        public Criteria andMminlowtrnIsNull() {
            addCriterion("mminLowTrn is null");
            return (Criteria) this;
        }

        public Criteria andMminlowtrnIsNotNull() {
            addCriterion("mminLowTrn is not null");
            return (Criteria) this;
        }

        public Criteria andMminlowtrnEqualTo(BigDecimal value) {
            addCriterion("mminLowTrn =", value, "mminlowtrn");
            return (Criteria) this;
        }

        public Criteria andMminlowtrnNotEqualTo(BigDecimal value) {
            addCriterion("mminLowTrn <>", value, "mminlowtrn");
            return (Criteria) this;
        }

        public Criteria andMminlowtrnGreaterThan(BigDecimal value) {
            addCriterion("mminLowTrn >", value, "mminlowtrn");
            return (Criteria) this;
        }

        public Criteria andMminlowtrnGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("mminLowTrn >=", value, "mminlowtrn");
            return (Criteria) this;
        }

        public Criteria andMminlowtrnLessThan(BigDecimal value) {
            addCriterion("mminLowTrn <", value, "mminlowtrn");
            return (Criteria) this;
        }

        public Criteria andMminlowtrnLessThanOrEqualTo(BigDecimal value) {
            addCriterion("mminLowTrn <=", value, "mminlowtrn");
            return (Criteria) this;
        }

        public Criteria andMminlowtrnIn(List<BigDecimal> values) {
            addCriterion("mminLowTrn in", values, "mminlowtrn");
            return (Criteria) this;
        }

        public Criteria andMminlowtrnNotIn(List<BigDecimal> values) {
            addCriterion("mminLowTrn not in", values, "mminlowtrn");
            return (Criteria) this;
        }

        public Criteria andMminlowtrnBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mminLowTrn between", value1, value2, "mminlowtrn");
            return (Criteria) this;
        }

        public Criteria andMminlowtrnNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mminLowTrn not between", value1, value2, "mminlowtrn");
            return (Criteria) this;
        }

        public Criteria andMminlowtrndateIsNull() {
            addCriterion("mminLowTrnDate is null");
            return (Criteria) this;
        }

        public Criteria andMminlowtrndateIsNotNull() {
            addCriterion("mminLowTrnDate is not null");
            return (Criteria) this;
        }

        public Criteria andMminlowtrndateEqualTo(String value) {
            addCriterion("mminLowTrnDate =", value, "mminlowtrndate");
            return (Criteria) this;
        }

        public Criteria andMminlowtrndateNotEqualTo(String value) {
            addCriterion("mminLowTrnDate <>", value, "mminlowtrndate");
            return (Criteria) this;
        }

        public Criteria andMminlowtrndateGreaterThan(String value) {
            addCriterion("mminLowTrnDate >", value, "mminlowtrndate");
            return (Criteria) this;
        }

        public Criteria andMminlowtrndateGreaterThanOrEqualTo(String value) {
            addCriterion("mminLowTrnDate >=", value, "mminlowtrndate");
            return (Criteria) this;
        }

        public Criteria andMminlowtrndateLessThan(String value) {
            addCriterion("mminLowTrnDate <", value, "mminlowtrndate");
            return (Criteria) this;
        }

        public Criteria andMminlowtrndateLessThanOrEqualTo(String value) {
            addCriterion("mminLowTrnDate <=", value, "mminlowtrndate");
            return (Criteria) this;
        }

        public Criteria andMminlowtrndateLike(String value) {
            addCriterion("mminLowTrnDate like", value, "mminlowtrndate");
            return (Criteria) this;
        }

        public Criteria andMminlowtrndateNotLike(String value) {
            addCriterion("mminLowTrnDate not like", value, "mminlowtrndate");
            return (Criteria) this;
        }

        public Criteria andMminlowtrndateIn(List<String> values) {
            addCriterion("mminLowTrnDate in", values, "mminlowtrndate");
            return (Criteria) this;
        }

        public Criteria andMminlowtrndateNotIn(List<String> values) {
            addCriterion("mminLowTrnDate not in", values, "mminlowtrndate");
            return (Criteria) this;
        }

        public Criteria andMminlowtrndateBetween(String value1, String value2) {
            addCriterion("mminLowTrnDate between", value1, value2, "mminlowtrndate");
            return (Criteria) this;
        }

        public Criteria andMminlowtrndateNotBetween(String value1, String value2) {
            addCriterion("mminLowTrnDate not between", value1, value2, "mminlowtrndate");
            return (Criteria) this;
        }

        public Criteria andMminlowtrnpreIsNull() {
            addCriterion("mminLowTrnPre is null");
            return (Criteria) this;
        }

        public Criteria andMminlowtrnpreIsNotNull() {
            addCriterion("mminLowTrnPre is not null");
            return (Criteria) this;
        }

        public Criteria andMminlowtrnpreEqualTo(BigDecimal value) {
            addCriterion("mminLowTrnPre =", value, "mminlowtrnpre");
            return (Criteria) this;
        }

        public Criteria andMminlowtrnpreNotEqualTo(BigDecimal value) {
            addCriterion("mminLowTrnPre <>", value, "mminlowtrnpre");
            return (Criteria) this;
        }

        public Criteria andMminlowtrnpreGreaterThan(BigDecimal value) {
            addCriterion("mminLowTrnPre >", value, "mminlowtrnpre");
            return (Criteria) this;
        }

        public Criteria andMminlowtrnpreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("mminLowTrnPre >=", value, "mminlowtrnpre");
            return (Criteria) this;
        }

        public Criteria andMminlowtrnpreLessThan(BigDecimal value) {
            addCriterion("mminLowTrnPre <", value, "mminlowtrnpre");
            return (Criteria) this;
        }

        public Criteria andMminlowtrnpreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("mminLowTrnPre <=", value, "mminlowtrnpre");
            return (Criteria) this;
        }

        public Criteria andMminlowtrnpreIn(List<BigDecimal> values) {
            addCriterion("mminLowTrnPre in", values, "mminlowtrnpre");
            return (Criteria) this;
        }

        public Criteria andMminlowtrnpreNotIn(List<BigDecimal> values) {
            addCriterion("mminLowTrnPre not in", values, "mminlowtrnpre");
            return (Criteria) this;
        }

        public Criteria andMminlowtrnpreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mminLowTrnPre between", value1, value2, "mminlowtrnpre");
            return (Criteria) this;
        }

        public Criteria andMminlowtrnpreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mminLowTrnPre not between", value1, value2, "mminlowtrnpre");
            return (Criteria) this;
        }

        public Criteria andMmintramtIsNull() {
            addCriterion("mminTrAmt is null");
            return (Criteria) this;
        }

        public Criteria andMmintramtIsNotNull() {
            addCriterion("mminTrAmt is not null");
            return (Criteria) this;
        }

        public Criteria andMmintramtEqualTo(BigDecimal value) {
            addCriterion("mminTrAmt =", value, "mmintramt");
            return (Criteria) this;
        }

        public Criteria andMmintramtNotEqualTo(BigDecimal value) {
            addCriterion("mminTrAmt <>", value, "mmintramt");
            return (Criteria) this;
        }

        public Criteria andMmintramtGreaterThan(BigDecimal value) {
            addCriterion("mminTrAmt >", value, "mmintramt");
            return (Criteria) this;
        }

        public Criteria andMmintramtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("mminTrAmt >=", value, "mmintramt");
            return (Criteria) this;
        }

        public Criteria andMmintramtLessThan(BigDecimal value) {
            addCriterion("mminTrAmt <", value, "mmintramt");
            return (Criteria) this;
        }

        public Criteria andMmintramtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("mminTrAmt <=", value, "mmintramt");
            return (Criteria) this;
        }

        public Criteria andMmintramtIn(List<BigDecimal> values) {
            addCriterion("mminTrAmt in", values, "mmintramt");
            return (Criteria) this;
        }

        public Criteria andMmintramtNotIn(List<BigDecimal> values) {
            addCriterion("mminTrAmt not in", values, "mmintramt");
            return (Criteria) this;
        }

        public Criteria andMmintramtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mminTrAmt between", value1, value2, "mmintramt");
            return (Criteria) this;
        }

        public Criteria andMmintramtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mminTrAmt not between", value1, value2, "mmintramt");
            return (Criteria) this;
        }

        public Criteria andMmintramtdateIsNull() {
            addCriterion("mminTrAmtDate is null");
            return (Criteria) this;
        }

        public Criteria andMmintramtdateIsNotNull() {
            addCriterion("mminTrAmtDate is not null");
            return (Criteria) this;
        }

        public Criteria andMmintramtdateEqualTo(String value) {
            addCriterion("mminTrAmtDate =", value, "mmintramtdate");
            return (Criteria) this;
        }

        public Criteria andMmintramtdateNotEqualTo(String value) {
            addCriterion("mminTrAmtDate <>", value, "mmintramtdate");
            return (Criteria) this;
        }

        public Criteria andMmintramtdateGreaterThan(String value) {
            addCriterion("mminTrAmtDate >", value, "mmintramtdate");
            return (Criteria) this;
        }

        public Criteria andMmintramtdateGreaterThanOrEqualTo(String value) {
            addCriterion("mminTrAmtDate >=", value, "mmintramtdate");
            return (Criteria) this;
        }

        public Criteria andMmintramtdateLessThan(String value) {
            addCriterion("mminTrAmtDate <", value, "mmintramtdate");
            return (Criteria) this;
        }

        public Criteria andMmintramtdateLessThanOrEqualTo(String value) {
            addCriterion("mminTrAmtDate <=", value, "mmintramtdate");
            return (Criteria) this;
        }

        public Criteria andMmintramtdateLike(String value) {
            addCriterion("mminTrAmtDate like", value, "mmintramtdate");
            return (Criteria) this;
        }

        public Criteria andMmintramtdateNotLike(String value) {
            addCriterion("mminTrAmtDate not like", value, "mmintramtdate");
            return (Criteria) this;
        }

        public Criteria andMmintramtdateIn(List<String> values) {
            addCriterion("mminTrAmtDate in", values, "mmintramtdate");
            return (Criteria) this;
        }

        public Criteria andMmintramtdateNotIn(List<String> values) {
            addCriterion("mminTrAmtDate not in", values, "mmintramtdate");
            return (Criteria) this;
        }

        public Criteria andMmintramtdateBetween(String value1, String value2) {
            addCriterion("mminTrAmtDate between", value1, value2, "mmintramtdate");
            return (Criteria) this;
        }

        public Criteria andMmintramtdateNotBetween(String value1, String value2) {
            addCriterion("mminTrAmtDate not between", value1, value2, "mmintramtdate");
            return (Criteria) this;
        }

        public Criteria andMmintramtpreIsNull() {
            addCriterion("mminTrAmtPre is null");
            return (Criteria) this;
        }

        public Criteria andMmintramtpreIsNotNull() {
            addCriterion("mminTrAmtPre is not null");
            return (Criteria) this;
        }

        public Criteria andMmintramtpreEqualTo(BigDecimal value) {
            addCriterion("mminTrAmtPre =", value, "mmintramtpre");
            return (Criteria) this;
        }

        public Criteria andMmintramtpreNotEqualTo(BigDecimal value) {
            addCriterion("mminTrAmtPre <>", value, "mmintramtpre");
            return (Criteria) this;
        }

        public Criteria andMmintramtpreGreaterThan(BigDecimal value) {
            addCriterion("mminTrAmtPre >", value, "mmintramtpre");
            return (Criteria) this;
        }

        public Criteria andMmintramtpreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("mminTrAmtPre >=", value, "mmintramtpre");
            return (Criteria) this;
        }

        public Criteria andMmintramtpreLessThan(BigDecimal value) {
            addCriterion("mminTrAmtPre <", value, "mmintramtpre");
            return (Criteria) this;
        }

        public Criteria andMmintramtpreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("mminTrAmtPre <=", value, "mmintramtpre");
            return (Criteria) this;
        }

        public Criteria andMmintramtpreIn(List<BigDecimal> values) {
            addCriterion("mminTrAmtPre in", values, "mmintramtpre");
            return (Criteria) this;
        }

        public Criteria andMmintramtpreNotIn(List<BigDecimal> values) {
            addCriterion("mminTrAmtPre not in", values, "mmintramtpre");
            return (Criteria) this;
        }

        public Criteria andMmintramtpreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mminTrAmtPre between", value1, value2, "mmintramtpre");
            return (Criteria) this;
        }

        public Criteria andMmintramtpreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mminTrAmtPre not between", value1, value2, "mmintramtpre");
            return (Criteria) this;
        }

        public Criteria andMmintrvolIsNull() {
            addCriterion("mminTrVol is null");
            return (Criteria) this;
        }

        public Criteria andMmintrvolIsNotNull() {
            addCriterion("mminTrVol is not null");
            return (Criteria) this;
        }

        public Criteria andMmintrvolEqualTo(BigDecimal value) {
            addCriterion("mminTrVol =", value, "mmintrvol");
            return (Criteria) this;
        }

        public Criteria andMmintrvolNotEqualTo(BigDecimal value) {
            addCriterion("mminTrVol <>", value, "mmintrvol");
            return (Criteria) this;
        }

        public Criteria andMmintrvolGreaterThan(BigDecimal value) {
            addCriterion("mminTrVol >", value, "mmintrvol");
            return (Criteria) this;
        }

        public Criteria andMmintrvolGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("mminTrVol >=", value, "mmintrvol");
            return (Criteria) this;
        }

        public Criteria andMmintrvolLessThan(BigDecimal value) {
            addCriterion("mminTrVol <", value, "mmintrvol");
            return (Criteria) this;
        }

        public Criteria andMmintrvolLessThanOrEqualTo(BigDecimal value) {
            addCriterion("mminTrVol <=", value, "mmintrvol");
            return (Criteria) this;
        }

        public Criteria andMmintrvolIn(List<BigDecimal> values) {
            addCriterion("mminTrVol in", values, "mmintrvol");
            return (Criteria) this;
        }

        public Criteria andMmintrvolNotIn(List<BigDecimal> values) {
            addCriterion("mminTrVol not in", values, "mmintrvol");
            return (Criteria) this;
        }

        public Criteria andMmintrvolBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mminTrVol between", value1, value2, "mmintrvol");
            return (Criteria) this;
        }

        public Criteria andMmintrvolNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mminTrVol not between", value1, value2, "mmintrvol");
            return (Criteria) this;
        }

        public Criteria andMmintrvoldateIsNull() {
            addCriterion("mminTrVolDate is null");
            return (Criteria) this;
        }

        public Criteria andMmintrvoldateIsNotNull() {
            addCriterion("mminTrVolDate is not null");
            return (Criteria) this;
        }

        public Criteria andMmintrvoldateEqualTo(String value) {
            addCriterion("mminTrVolDate =", value, "mmintrvoldate");
            return (Criteria) this;
        }

        public Criteria andMmintrvoldateNotEqualTo(String value) {
            addCriterion("mminTrVolDate <>", value, "mmintrvoldate");
            return (Criteria) this;
        }

        public Criteria andMmintrvoldateGreaterThan(String value) {
            addCriterion("mminTrVolDate >", value, "mmintrvoldate");
            return (Criteria) this;
        }

        public Criteria andMmintrvoldateGreaterThanOrEqualTo(String value) {
            addCriterion("mminTrVolDate >=", value, "mmintrvoldate");
            return (Criteria) this;
        }

        public Criteria andMmintrvoldateLessThan(String value) {
            addCriterion("mminTrVolDate <", value, "mmintrvoldate");
            return (Criteria) this;
        }

        public Criteria andMmintrvoldateLessThanOrEqualTo(String value) {
            addCriterion("mminTrVolDate <=", value, "mmintrvoldate");
            return (Criteria) this;
        }

        public Criteria andMmintrvoldateLike(String value) {
            addCriterion("mminTrVolDate like", value, "mmintrvoldate");
            return (Criteria) this;
        }

        public Criteria andMmintrvoldateNotLike(String value) {
            addCriterion("mminTrVolDate not like", value, "mmintrvoldate");
            return (Criteria) this;
        }

        public Criteria andMmintrvoldateIn(List<String> values) {
            addCriterion("mminTrVolDate in", values, "mmintrvoldate");
            return (Criteria) this;
        }

        public Criteria andMmintrvoldateNotIn(List<String> values) {
            addCriterion("mminTrVolDate not in", values, "mmintrvoldate");
            return (Criteria) this;
        }

        public Criteria andMmintrvoldateBetween(String value1, String value2) {
            addCriterion("mminTrVolDate between", value1, value2, "mmintrvoldate");
            return (Criteria) this;
        }

        public Criteria andMmintrvoldateNotBetween(String value1, String value2) {
            addCriterion("mminTrVolDate not between", value1, value2, "mmintrvoldate");
            return (Criteria) this;
        }

        public Criteria andMmintrvolpreIsNull() {
            addCriterion("mminTrVolPre is null");
            return (Criteria) this;
        }

        public Criteria andMmintrvolpreIsNotNull() {
            addCriterion("mminTrVolPre is not null");
            return (Criteria) this;
        }

        public Criteria andMmintrvolpreEqualTo(BigDecimal value) {
            addCriterion("mminTrVolPre =", value, "mmintrvolpre");
            return (Criteria) this;
        }

        public Criteria andMmintrvolpreNotEqualTo(BigDecimal value) {
            addCriterion("mminTrVolPre <>", value, "mmintrvolpre");
            return (Criteria) this;
        }

        public Criteria andMmintrvolpreGreaterThan(BigDecimal value) {
            addCriterion("mminTrVolPre >", value, "mmintrvolpre");
            return (Criteria) this;
        }

        public Criteria andMmintrvolpreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("mminTrVolPre >=", value, "mmintrvolpre");
            return (Criteria) this;
        }

        public Criteria andMmintrvolpreLessThan(BigDecimal value) {
            addCriterion("mminTrVolPre <", value, "mmintrvolpre");
            return (Criteria) this;
        }

        public Criteria andMmintrvolpreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("mminTrVolPre <=", value, "mmintrvolpre");
            return (Criteria) this;
        }

        public Criteria andMmintrvolpreIn(List<BigDecimal> values) {
            addCriterion("mminTrVolPre in", values, "mmintrvolpre");
            return (Criteria) this;
        }

        public Criteria andMmintrvolpreNotIn(List<BigDecimal> values) {
            addCriterion("mminTrVolPre not in", values, "mmintrvolpre");
            return (Criteria) this;
        }

        public Criteria andMmintrvolpreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mminTrVolPre between", value1, value2, "mmintrvolpre");
            return (Criteria) this;
        }

        public Criteria andMmintrvolpreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mminTrVolPre not between", value1, value2, "mmintrvolpre");
            return (Criteria) this;
        }

        public Criteria andMnegotiablevalueIsNull() {
            addCriterion("mnegotiableValue is null");
            return (Criteria) this;
        }

        public Criteria andMnegotiablevalueIsNotNull() {
            addCriterion("mnegotiableValue is not null");
            return (Criteria) this;
        }

        public Criteria andMnegotiablevalueEqualTo(BigDecimal value) {
            addCriterion("mnegotiableValue =", value, "mnegotiablevalue");
            return (Criteria) this;
        }

        public Criteria andMnegotiablevalueNotEqualTo(BigDecimal value) {
            addCriterion("mnegotiableValue <>", value, "mnegotiablevalue");
            return (Criteria) this;
        }

        public Criteria andMnegotiablevalueGreaterThan(BigDecimal value) {
            addCriterion("mnegotiableValue >", value, "mnegotiablevalue");
            return (Criteria) this;
        }

        public Criteria andMnegotiablevalueGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("mnegotiableValue >=", value, "mnegotiablevalue");
            return (Criteria) this;
        }

        public Criteria andMnegotiablevalueLessThan(BigDecimal value) {
            addCriterion("mnegotiableValue <", value, "mnegotiablevalue");
            return (Criteria) this;
        }

        public Criteria andMnegotiablevalueLessThanOrEqualTo(BigDecimal value) {
            addCriterion("mnegotiableValue <=", value, "mnegotiablevalue");
            return (Criteria) this;
        }

        public Criteria andMnegotiablevalueIn(List<BigDecimal> values) {
            addCriterion("mnegotiableValue in", values, "mnegotiablevalue");
            return (Criteria) this;
        }

        public Criteria andMnegotiablevalueNotIn(List<BigDecimal> values) {
            addCriterion("mnegotiableValue not in", values, "mnegotiablevalue");
            return (Criteria) this;
        }

        public Criteria andMnegotiablevalueBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mnegotiableValue between", value1, value2, "mnegotiablevalue");
            return (Criteria) this;
        }

        public Criteria andMnegotiablevalueNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mnegotiableValue not between", value1, value2, "mnegotiablevalue");
            return (Criteria) this;
        }

        public Criteria andMnegotiablevaluepreIsNull() {
            addCriterion("mnegotiableValuePre is null");
            return (Criteria) this;
        }

        public Criteria andMnegotiablevaluepreIsNotNull() {
            addCriterion("mnegotiableValuePre is not null");
            return (Criteria) this;
        }

        public Criteria andMnegotiablevaluepreEqualTo(BigDecimal value) {
            addCriterion("mnegotiableValuePre =", value, "mnegotiablevaluepre");
            return (Criteria) this;
        }

        public Criteria andMnegotiablevaluepreNotEqualTo(BigDecimal value) {
            addCriterion("mnegotiableValuePre <>", value, "mnegotiablevaluepre");
            return (Criteria) this;
        }

        public Criteria andMnegotiablevaluepreGreaterThan(BigDecimal value) {
            addCriterion("mnegotiableValuePre >", value, "mnegotiablevaluepre");
            return (Criteria) this;
        }

        public Criteria andMnegotiablevaluepreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("mnegotiableValuePre >=", value, "mnegotiablevaluepre");
            return (Criteria) this;
        }

        public Criteria andMnegotiablevaluepreLessThan(BigDecimal value) {
            addCriterion("mnegotiableValuePre <", value, "mnegotiablevaluepre");
            return (Criteria) this;
        }

        public Criteria andMnegotiablevaluepreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("mnegotiableValuePre <=", value, "mnegotiablevaluepre");
            return (Criteria) this;
        }

        public Criteria andMnegotiablevaluepreIn(List<BigDecimal> values) {
            addCriterion("mnegotiableValuePre in", values, "mnegotiablevaluepre");
            return (Criteria) this;
        }

        public Criteria andMnegotiablevaluepreNotIn(List<BigDecimal> values) {
            addCriterion("mnegotiableValuePre not in", values, "mnegotiablevaluepre");
            return (Criteria) this;
        }

        public Criteria andMnegotiablevaluepreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mnegotiableValuePre between", value1, value2, "mnegotiablevaluepre");
            return (Criteria) this;
        }

        public Criteria andMnegotiablevaluepreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mnegotiableValuePre not between", value1, value2, "mnegotiablevaluepre");
            return (Criteria) this;
        }

        public Criteria andMprofitrateIsNull() {
            addCriterion("mprofitRate is null");
            return (Criteria) this;
        }

        public Criteria andMprofitrateIsNotNull() {
            addCriterion("mprofitRate is not null");
            return (Criteria) this;
        }

        public Criteria andMprofitrateEqualTo(String value) {
            addCriterion("mprofitRate =", value, "mprofitrate");
            return (Criteria) this;
        }

        public Criteria andMprofitrateNotEqualTo(String value) {
            addCriterion("mprofitRate <>", value, "mprofitrate");
            return (Criteria) this;
        }

        public Criteria andMprofitrateGreaterThan(String value) {
            addCriterion("mprofitRate >", value, "mprofitrate");
            return (Criteria) this;
        }

        public Criteria andMprofitrateGreaterThanOrEqualTo(String value) {
            addCriterion("mprofitRate >=", value, "mprofitrate");
            return (Criteria) this;
        }

        public Criteria andMprofitrateLessThan(String value) {
            addCriterion("mprofitRate <", value, "mprofitrate");
            return (Criteria) this;
        }

        public Criteria andMprofitrateLessThanOrEqualTo(String value) {
            addCriterion("mprofitRate <=", value, "mprofitrate");
            return (Criteria) this;
        }

        public Criteria andMprofitrateLike(String value) {
            addCriterion("mprofitRate like", value, "mprofitrate");
            return (Criteria) this;
        }

        public Criteria andMprofitrateNotLike(String value) {
            addCriterion("mprofitRate not like", value, "mprofitrate");
            return (Criteria) this;
        }

        public Criteria andMprofitrateIn(List<String> values) {
            addCriterion("mprofitRate in", values, "mprofitrate");
            return (Criteria) this;
        }

        public Criteria andMprofitrateNotIn(List<String> values) {
            addCriterion("mprofitRate not in", values, "mprofitrate");
            return (Criteria) this;
        }

        public Criteria andMprofitrateBetween(String value1, String value2) {
            addCriterion("mprofitRate between", value1, value2, "mprofitrate");
            return (Criteria) this;
        }

        public Criteria andMprofitrateNotBetween(String value1, String value2) {
            addCriterion("mprofitRate not between", value1, value2, "mprofitrate");
            return (Criteria) this;
        }

        public Criteria andMprofitratepreIsNull() {
            addCriterion("mprofitRatePre is null");
            return (Criteria) this;
        }

        public Criteria andMprofitratepreIsNotNull() {
            addCriterion("mprofitRatePre is not null");
            return (Criteria) this;
        }

        public Criteria andMprofitratepreEqualTo(String value) {
            addCriterion("mprofitRatePre =", value, "mprofitratepre");
            return (Criteria) this;
        }

        public Criteria andMprofitratepreNotEqualTo(String value) {
            addCriterion("mprofitRatePre <>", value, "mprofitratepre");
            return (Criteria) this;
        }

        public Criteria andMprofitratepreGreaterThan(String value) {
            addCriterion("mprofitRatePre >", value, "mprofitratepre");
            return (Criteria) this;
        }

        public Criteria andMprofitratepreGreaterThanOrEqualTo(String value) {
            addCriterion("mprofitRatePre >=", value, "mprofitratepre");
            return (Criteria) this;
        }

        public Criteria andMprofitratepreLessThan(String value) {
            addCriterion("mprofitRatePre <", value, "mprofitratepre");
            return (Criteria) this;
        }

        public Criteria andMprofitratepreLessThanOrEqualTo(String value) {
            addCriterion("mprofitRatePre <=", value, "mprofitratepre");
            return (Criteria) this;
        }

        public Criteria andMprofitratepreLike(String value) {
            addCriterion("mprofitRatePre like", value, "mprofitratepre");
            return (Criteria) this;
        }

        public Criteria andMprofitratepreNotLike(String value) {
            addCriterion("mprofitRatePre not like", value, "mprofitratepre");
            return (Criteria) this;
        }

        public Criteria andMprofitratepreIn(List<String> values) {
            addCriterion("mprofitRatePre in", values, "mprofitratepre");
            return (Criteria) this;
        }

        public Criteria andMprofitratepreNotIn(List<String> values) {
            addCriterion("mprofitRatePre not in", values, "mprofitratepre");
            return (Criteria) this;
        }

        public Criteria andMprofitratepreBetween(String value1, String value2) {
            addCriterion("mprofitRatePre between", value1, value2, "mprofitratepre");
            return (Criteria) this;
        }

        public Criteria andMprofitratepreNotBetween(String value1, String value2) {
            addCriterion("mprofitRatePre not between", value1, value2, "mprofitratepre");
            return (Criteria) this;
        }

        public Criteria andMtotalamtIsNull() {
            addCriterion("mtotalAmt is null");
            return (Criteria) this;
        }

        public Criteria andMtotalamtIsNotNull() {
            addCriterion("mtotalAmt is not null");
            return (Criteria) this;
        }

        public Criteria andMtotalamtEqualTo(BigDecimal value) {
            addCriterion("mtotalAmt =", value, "mtotalamt");
            return (Criteria) this;
        }

        public Criteria andMtotalamtNotEqualTo(BigDecimal value) {
            addCriterion("mtotalAmt <>", value, "mtotalamt");
            return (Criteria) this;
        }

        public Criteria andMtotalamtGreaterThan(BigDecimal value) {
            addCriterion("mtotalAmt >", value, "mtotalamt");
            return (Criteria) this;
        }

        public Criteria andMtotalamtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("mtotalAmt >=", value, "mtotalamt");
            return (Criteria) this;
        }

        public Criteria andMtotalamtLessThan(BigDecimal value) {
            addCriterion("mtotalAmt <", value, "mtotalamt");
            return (Criteria) this;
        }

        public Criteria andMtotalamtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("mtotalAmt <=", value, "mtotalamt");
            return (Criteria) this;
        }

        public Criteria andMtotalamtIn(List<BigDecimal> values) {
            addCriterion("mtotalAmt in", values, "mtotalamt");
            return (Criteria) this;
        }

        public Criteria andMtotalamtNotIn(List<BigDecimal> values) {
            addCriterion("mtotalAmt not in", values, "mtotalamt");
            return (Criteria) this;
        }

        public Criteria andMtotalamtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mtotalAmt between", value1, value2, "mtotalamt");
            return (Criteria) this;
        }

        public Criteria andMtotalamtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mtotalAmt not between", value1, value2, "mtotalamt");
            return (Criteria) this;
        }

        public Criteria andMtotalamtpreIsNull() {
            addCriterion("mtotalAmtPre is null");
            return (Criteria) this;
        }

        public Criteria andMtotalamtpreIsNotNull() {
            addCriterion("mtotalAmtPre is not null");
            return (Criteria) this;
        }

        public Criteria andMtotalamtpreEqualTo(BigDecimal value) {
            addCriterion("mtotalAmtPre =", value, "mtotalamtpre");
            return (Criteria) this;
        }

        public Criteria andMtotalamtpreNotEqualTo(BigDecimal value) {
            addCriterion("mtotalAmtPre <>", value, "mtotalamtpre");
            return (Criteria) this;
        }

        public Criteria andMtotalamtpreGreaterThan(BigDecimal value) {
            addCriterion("mtotalAmtPre >", value, "mtotalamtpre");
            return (Criteria) this;
        }

        public Criteria andMtotalamtpreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("mtotalAmtPre >=", value, "mtotalamtpre");
            return (Criteria) this;
        }

        public Criteria andMtotalamtpreLessThan(BigDecimal value) {
            addCriterion("mtotalAmtPre <", value, "mtotalamtpre");
            return (Criteria) this;
        }

        public Criteria andMtotalamtpreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("mtotalAmtPre <=", value, "mtotalamtpre");
            return (Criteria) this;
        }

        public Criteria andMtotalamtpreIn(List<BigDecimal> values) {
            addCriterion("mtotalAmtPre in", values, "mtotalamtpre");
            return (Criteria) this;
        }

        public Criteria andMtotalamtpreNotIn(List<BigDecimal> values) {
            addCriterion("mtotalAmtPre not in", values, "mtotalamtpre");
            return (Criteria) this;
        }

        public Criteria andMtotalamtpreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mtotalAmtPre between", value1, value2, "mtotalamtpre");
            return (Criteria) this;
        }

        public Criteria andMtotalamtpreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mtotalAmtPre not between", value1, value2, "mtotalamtpre");
            return (Criteria) this;
        }

        public Criteria andMtotaltxIsNull() {
            addCriterion("mtotalTx is null");
            return (Criteria) this;
        }

        public Criteria andMtotaltxIsNotNull() {
            addCriterion("mtotalTx is not null");
            return (Criteria) this;
        }

        public Criteria andMtotaltxEqualTo(BigDecimal value) {
            addCriterion("mtotalTx =", value, "mtotaltx");
            return (Criteria) this;
        }

        public Criteria andMtotaltxNotEqualTo(BigDecimal value) {
            addCriterion("mtotalTx <>", value, "mtotaltx");
            return (Criteria) this;
        }

        public Criteria andMtotaltxGreaterThan(BigDecimal value) {
            addCriterion("mtotalTx >", value, "mtotaltx");
            return (Criteria) this;
        }

        public Criteria andMtotaltxGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("mtotalTx >=", value, "mtotaltx");
            return (Criteria) this;
        }

        public Criteria andMtotaltxLessThan(BigDecimal value) {
            addCriterion("mtotalTx <", value, "mtotaltx");
            return (Criteria) this;
        }

        public Criteria andMtotaltxLessThanOrEqualTo(BigDecimal value) {
            addCriterion("mtotalTx <=", value, "mtotaltx");
            return (Criteria) this;
        }

        public Criteria andMtotaltxIn(List<BigDecimal> values) {
            addCriterion("mtotalTx in", values, "mtotaltx");
            return (Criteria) this;
        }

        public Criteria andMtotaltxNotIn(List<BigDecimal> values) {
            addCriterion("mtotalTx not in", values, "mtotaltx");
            return (Criteria) this;
        }

        public Criteria andMtotaltxBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mtotalTx between", value1, value2, "mtotaltx");
            return (Criteria) this;
        }

        public Criteria andMtotaltxNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mtotalTx not between", value1, value2, "mtotaltx");
            return (Criteria) this;
        }

        public Criteria andMtotaltxdateIsNull() {
            addCriterion("mtotalTxDate is null");
            return (Criteria) this;
        }

        public Criteria andMtotaltxdateIsNotNull() {
            addCriterion("mtotalTxDate is not null");
            return (Criteria) this;
        }

        public Criteria andMtotaltxdateEqualTo(String value) {
            addCriterion("mtotalTxDate =", value, "mtotaltxdate");
            return (Criteria) this;
        }

        public Criteria andMtotaltxdateNotEqualTo(String value) {
            addCriterion("mtotalTxDate <>", value, "mtotaltxdate");
            return (Criteria) this;
        }

        public Criteria andMtotaltxdateGreaterThan(String value) {
            addCriterion("mtotalTxDate >", value, "mtotaltxdate");
            return (Criteria) this;
        }

        public Criteria andMtotaltxdateGreaterThanOrEqualTo(String value) {
            addCriterion("mtotalTxDate >=", value, "mtotaltxdate");
            return (Criteria) this;
        }

        public Criteria andMtotaltxdateLessThan(String value) {
            addCriterion("mtotalTxDate <", value, "mtotaltxdate");
            return (Criteria) this;
        }

        public Criteria andMtotaltxdateLessThanOrEqualTo(String value) {
            addCriterion("mtotalTxDate <=", value, "mtotaltxdate");
            return (Criteria) this;
        }

        public Criteria andMtotaltxdateLike(String value) {
            addCriterion("mtotalTxDate like", value, "mtotaltxdate");
            return (Criteria) this;
        }

        public Criteria andMtotaltxdateNotLike(String value) {
            addCriterion("mtotalTxDate not like", value, "mtotaltxdate");
            return (Criteria) this;
        }

        public Criteria andMtotaltxdateIn(List<String> values) {
            addCriterion("mtotalTxDate in", values, "mtotaltxdate");
            return (Criteria) this;
        }

        public Criteria andMtotaltxdateNotIn(List<String> values) {
            addCriterion("mtotalTxDate not in", values, "mtotaltxdate");
            return (Criteria) this;
        }

        public Criteria andMtotaltxdateBetween(String value1, String value2) {
            addCriterion("mtotalTxDate between", value1, value2, "mtotaltxdate");
            return (Criteria) this;
        }

        public Criteria andMtotaltxdateNotBetween(String value1, String value2) {
            addCriterion("mtotalTxDate not between", value1, value2, "mtotaltxdate");
            return (Criteria) this;
        }

        public Criteria andMtotaltxpreIsNull() {
            addCriterion("mtotalTxPre is null");
            return (Criteria) this;
        }

        public Criteria andMtotaltxpreIsNotNull() {
            addCriterion("mtotalTxPre is not null");
            return (Criteria) this;
        }

        public Criteria andMtotaltxpreEqualTo(BigDecimal value) {
            addCriterion("mtotalTxPre =", value, "mtotaltxpre");
            return (Criteria) this;
        }

        public Criteria andMtotaltxpreNotEqualTo(BigDecimal value) {
            addCriterion("mtotalTxPre <>", value, "mtotaltxpre");
            return (Criteria) this;
        }

        public Criteria andMtotaltxpreGreaterThan(BigDecimal value) {
            addCriterion("mtotalTxPre >", value, "mtotaltxpre");
            return (Criteria) this;
        }

        public Criteria andMtotaltxpreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("mtotalTxPre >=", value, "mtotaltxpre");
            return (Criteria) this;
        }

        public Criteria andMtotaltxpreLessThan(BigDecimal value) {
            addCriterion("mtotalTxPre <", value, "mtotaltxpre");
            return (Criteria) this;
        }

        public Criteria andMtotaltxpreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("mtotalTxPre <=", value, "mtotaltxpre");
            return (Criteria) this;
        }

        public Criteria andMtotaltxpreIn(List<BigDecimal> values) {
            addCriterion("mtotalTxPre in", values, "mtotaltxpre");
            return (Criteria) this;
        }

        public Criteria andMtotaltxpreNotIn(List<BigDecimal> values) {
            addCriterion("mtotalTxPre not in", values, "mtotaltxpre");
            return (Criteria) this;
        }

        public Criteria andMtotaltxpreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mtotalTxPre between", value1, value2, "mtotaltxpre");
            return (Criteria) this;
        }

        public Criteria andMtotaltxpreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mtotalTxPre not between", value1, value2, "mtotaltxpre");
            return (Criteria) this;
        }

        public Criteria andMtotalvolIsNull() {
            addCriterion("mtotalVol is null");
            return (Criteria) this;
        }

        public Criteria andMtotalvolIsNotNull() {
            addCriterion("mtotalVol is not null");
            return (Criteria) this;
        }

        public Criteria andMtotalvolEqualTo(BigDecimal value) {
            addCriterion("mtotalVol =", value, "mtotalvol");
            return (Criteria) this;
        }

        public Criteria andMtotalvolNotEqualTo(BigDecimal value) {
            addCriterion("mtotalVol <>", value, "mtotalvol");
            return (Criteria) this;
        }

        public Criteria andMtotalvolGreaterThan(BigDecimal value) {
            addCriterion("mtotalVol >", value, "mtotalvol");
            return (Criteria) this;
        }

        public Criteria andMtotalvolGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("mtotalVol >=", value, "mtotalvol");
            return (Criteria) this;
        }

        public Criteria andMtotalvolLessThan(BigDecimal value) {
            addCriterion("mtotalVol <", value, "mtotalvol");
            return (Criteria) this;
        }

        public Criteria andMtotalvolLessThanOrEqualTo(BigDecimal value) {
            addCriterion("mtotalVol <=", value, "mtotalvol");
            return (Criteria) this;
        }

        public Criteria andMtotalvolIn(List<BigDecimal> values) {
            addCriterion("mtotalVol in", values, "mtotalvol");
            return (Criteria) this;
        }

        public Criteria andMtotalvolNotIn(List<BigDecimal> values) {
            addCriterion("mtotalVol not in", values, "mtotalvol");
            return (Criteria) this;
        }

        public Criteria andMtotalvolBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mtotalVol between", value1, value2, "mtotalvol");
            return (Criteria) this;
        }

        public Criteria andMtotalvolNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mtotalVol not between", value1, value2, "mtotalvol");
            return (Criteria) this;
        }

        public Criteria andMtotalvolpreIsNull() {
            addCriterion("mtotalVolPre is null");
            return (Criteria) this;
        }

        public Criteria andMtotalvolpreIsNotNull() {
            addCriterion("mtotalVolPre is not null");
            return (Criteria) this;
        }

        public Criteria andMtotalvolpreEqualTo(BigDecimal value) {
            addCriterion("mtotalVolPre =", value, "mtotalvolpre");
            return (Criteria) this;
        }

        public Criteria andMtotalvolpreNotEqualTo(BigDecimal value) {
            addCriterion("mtotalVolPre <>", value, "mtotalvolpre");
            return (Criteria) this;
        }

        public Criteria andMtotalvolpreGreaterThan(BigDecimal value) {
            addCriterion("mtotalVolPre >", value, "mtotalvolpre");
            return (Criteria) this;
        }

        public Criteria andMtotalvolpreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("mtotalVolPre >=", value, "mtotalvolpre");
            return (Criteria) this;
        }

        public Criteria andMtotalvolpreLessThan(BigDecimal value) {
            addCriterion("mtotalVolPre <", value, "mtotalvolpre");
            return (Criteria) this;
        }

        public Criteria andMtotalvolpreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("mtotalVolPre <=", value, "mtotalvolpre");
            return (Criteria) this;
        }

        public Criteria andMtotalvolpreIn(List<BigDecimal> values) {
            addCriterion("mtotalVolPre in", values, "mtotalvolpre");
            return (Criteria) this;
        }

        public Criteria andMtotalvolpreNotIn(List<BigDecimal> values) {
            addCriterion("mtotalVolPre not in", values, "mtotalvolpre");
            return (Criteria) this;
        }

        public Criteria andMtotalvolpreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mtotalVolPre between", value1, value2, "mtotalvolpre");
            return (Criteria) this;
        }

        public Criteria andMtotalvolpreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mtotalVolPre not between", value1, value2, "mtotalvolpre");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jijin_monthly
     *
     * @mbg.generated do_not_delete_during_merge Sun Oct 08 13:47:39 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jijin_monthly
     *
     * @mbg.generated Sun Oct 08 13:47:39 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}