package com.autumnsinger.dal.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class JijinDailyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jijin_daily
     *
     * @mbg.generated Sun Oct 08 13:47:38 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jijin_daily
     *
     * @mbg.generated Sun Oct 08 13:47:38 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jijin_daily
     *
     * @mbg.generated Sun Oct 08 13:47:38 CST 2017
     */
    protected List<Criteria> oredCriteria;

    private Integer limit;

    private Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jijin_daily
     *
     * @mbg.generated Sun Oct 08 13:47:38 CST 2017
     */
    public JijinDailyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jijin_daily
     *
     * @mbg.generated Sun Oct 08 13:47:38 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jijin_daily
     *
     * @mbg.generated Sun Oct 08 13:47:38 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jijin_daily
     *
     * @mbg.generated Sun Oct 08 13:47:38 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jijin_daily
     *
     * @mbg.generated Sun Oct 08 13:47:38 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jijin_daily
     *
     * @mbg.generated Sun Oct 08 13:47:38 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jijin_daily
     *
     * @mbg.generated Sun Oct 08 13:47:38 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jijin_daily
     *
     * @mbg.generated Sun Oct 08 13:47:38 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jijin_daily
     *
     * @mbg.generated Sun Oct 08 13:47:38 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jijin_daily
     *
     * @mbg.generated Sun Oct 08 13:47:38 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jijin_daily
     *
     * @mbg.generated Sun Oct 08 13:47:38 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jijin_daily
     *
     * @mbg.generated Sun Oct 08 13:47:38 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSearchdateIsNull() {
            addCriterion("searchDate is null");
            return (Criteria) this;
        }

        public Criteria andSearchdateIsNotNull() {
            addCriterion("searchDate is not null");
            return (Criteria) this;
        }

        public Criteria andSearchdateEqualTo(String value) {
            addCriterion("searchDate =", value, "searchdate");
            return (Criteria) this;
        }

        public Criteria andSearchdateNotEqualTo(String value) {
            addCriterion("searchDate <>", value, "searchdate");
            return (Criteria) this;
        }

        public Criteria andSearchdateGreaterThan(String value) {
            addCriterion("searchDate >", value, "searchdate");
            return (Criteria) this;
        }

        public Criteria andSearchdateGreaterThanOrEqualTo(String value) {
            addCriterion("searchDate >=", value, "searchdate");
            return (Criteria) this;
        }

        public Criteria andSearchdateLessThan(String value) {
            addCriterion("searchDate <", value, "searchdate");
            return (Criteria) this;
        }

        public Criteria andSearchdateLessThanOrEqualTo(String value) {
            addCriterion("searchDate <=", value, "searchdate");
            return (Criteria) this;
        }

        public Criteria andSearchdateLike(String value) {
            addCriterion("searchDate like", value, "searchdate");
            return (Criteria) this;
        }

        public Criteria andSearchdateNotLike(String value) {
            addCriterion("searchDate not like", value, "searchdate");
            return (Criteria) this;
        }

        public Criteria andSearchdateIn(List<String> values) {
            addCriterion("searchDate in", values, "searchdate");
            return (Criteria) this;
        }

        public Criteria andSearchdateNotIn(List<String> values) {
            addCriterion("searchDate not in", values, "searchdate");
            return (Criteria) this;
        }

        public Criteria andSearchdateBetween(String value1, String value2) {
            addCriterion("searchDate between", value1, value2, "searchdate");
            return (Criteria) this;
        }

        public Criteria andSearchdateNotBetween(String value1, String value2) {
            addCriterion("searchDate not between", value1, value2, "searchdate");
            return (Criteria) this;
        }

        public Criteria andProducttypeIsNull() {
            addCriterion("productType is null");
            return (Criteria) this;
        }

        public Criteria andProducttypeIsNotNull() {
            addCriterion("productType is not null");
            return (Criteria) this;
        }

        public Criteria andProducttypeEqualTo(String value) {
            addCriterion("productType =", value, "producttype");
            return (Criteria) this;
        }

        public Criteria andProducttypeNotEqualTo(String value) {
            addCriterion("productType <>", value, "producttype");
            return (Criteria) this;
        }

        public Criteria andProducttypeGreaterThan(String value) {
            addCriterion("productType >", value, "producttype");
            return (Criteria) this;
        }

        public Criteria andProducttypeGreaterThanOrEqualTo(String value) {
            addCriterion("productType >=", value, "producttype");
            return (Criteria) this;
        }

        public Criteria andProducttypeLessThan(String value) {
            addCriterion("productType <", value, "producttype");
            return (Criteria) this;
        }

        public Criteria andProducttypeLessThanOrEqualTo(String value) {
            addCriterion("productType <=", value, "producttype");
            return (Criteria) this;
        }

        public Criteria andProducttypeLike(String value) {
            addCriterion("productType like", value, "producttype");
            return (Criteria) this;
        }

        public Criteria andProducttypeNotLike(String value) {
            addCriterion("productType not like", value, "producttype");
            return (Criteria) this;
        }

        public Criteria andProducttypeIn(List<String> values) {
            addCriterion("productType in", values, "producttype");
            return (Criteria) this;
        }

        public Criteria andProducttypeNotIn(List<String> values) {
            addCriterion("productType not in", values, "producttype");
            return (Criteria) this;
        }

        public Criteria andProducttypeBetween(String value1, String value2) {
            addCriterion("productType between", value1, value2, "producttype");
            return (Criteria) this;
        }

        public Criteria andProducttypeNotBetween(String value1, String value2) {
            addCriterion("productType not between", value1, value2, "producttype");
            return (Criteria) this;
        }

        public Criteria andTrdvolIsNull() {
            addCriterion("trdVol is null");
            return (Criteria) this;
        }

        public Criteria andTrdvolIsNotNull() {
            addCriterion("trdVol is not null");
            return (Criteria) this;
        }

        public Criteria andTrdvolEqualTo(BigDecimal value) {
            addCriterion("trdVol =", value, "trdvol");
            return (Criteria) this;
        }

        public Criteria andTrdvolNotEqualTo(BigDecimal value) {
            addCriterion("trdVol <>", value, "trdvol");
            return (Criteria) this;
        }

        public Criteria andTrdvolGreaterThan(BigDecimal value) {
            addCriterion("trdVol >", value, "trdvol");
            return (Criteria) this;
        }

        public Criteria andTrdvolGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("trdVol >=", value, "trdvol");
            return (Criteria) this;
        }

        public Criteria andTrdvolLessThan(BigDecimal value) {
            addCriterion("trdVol <", value, "trdvol");
            return (Criteria) this;
        }

        public Criteria andTrdvolLessThanOrEqualTo(BigDecimal value) {
            addCriterion("trdVol <=", value, "trdvol");
            return (Criteria) this;
        }

        public Criteria andTrdvolIn(List<BigDecimal> values) {
            addCriterion("trdVol in", values, "trdvol");
            return (Criteria) this;
        }

        public Criteria andTrdvolNotIn(List<BigDecimal> values) {
            addCriterion("trdVol not in", values, "trdvol");
            return (Criteria) this;
        }

        public Criteria andTrdvolBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("trdVol between", value1, value2, "trdvol");
            return (Criteria) this;
        }

        public Criteria andTrdvolNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("trdVol not between", value1, value2, "trdvol");
            return (Criteria) this;
        }

        public Criteria andTrdvol1IsNull() {
            addCriterion("trdVol1 is null");
            return (Criteria) this;
        }

        public Criteria andTrdvol1IsNotNull() {
            addCriterion("trdVol1 is not null");
            return (Criteria) this;
        }

        public Criteria andTrdvol1EqualTo(BigDecimal value) {
            addCriterion("trdVol1 =", value, "trdvol1");
            return (Criteria) this;
        }

        public Criteria andTrdvol1NotEqualTo(BigDecimal value) {
            addCriterion("trdVol1 <>", value, "trdvol1");
            return (Criteria) this;
        }

        public Criteria andTrdvol1GreaterThan(BigDecimal value) {
            addCriterion("trdVol1 >", value, "trdvol1");
            return (Criteria) this;
        }

        public Criteria andTrdvol1GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("trdVol1 >=", value, "trdvol1");
            return (Criteria) this;
        }

        public Criteria andTrdvol1LessThan(BigDecimal value) {
            addCriterion("trdVol1 <", value, "trdvol1");
            return (Criteria) this;
        }

        public Criteria andTrdvol1LessThanOrEqualTo(BigDecimal value) {
            addCriterion("trdVol1 <=", value, "trdvol1");
            return (Criteria) this;
        }

        public Criteria andTrdvol1In(List<BigDecimal> values) {
            addCriterion("trdVol1 in", values, "trdvol1");
            return (Criteria) this;
        }

        public Criteria andTrdvol1NotIn(List<BigDecimal> values) {
            addCriterion("trdVol1 not in", values, "trdvol1");
            return (Criteria) this;
        }

        public Criteria andTrdvol1Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("trdVol1 between", value1, value2, "trdvol1");
            return (Criteria) this;
        }

        public Criteria andTrdvol1NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("trdVol1 not between", value1, value2, "trdvol1");
            return (Criteria) this;
        }

        public Criteria andTrdamtIsNull() {
            addCriterion("trdAmt is null");
            return (Criteria) this;
        }

        public Criteria andTrdamtIsNotNull() {
            addCriterion("trdAmt is not null");
            return (Criteria) this;
        }

        public Criteria andTrdamtEqualTo(BigDecimal value) {
            addCriterion("trdAmt =", value, "trdamt");
            return (Criteria) this;
        }

        public Criteria andTrdamtNotEqualTo(BigDecimal value) {
            addCriterion("trdAmt <>", value, "trdamt");
            return (Criteria) this;
        }

        public Criteria andTrdamtGreaterThan(BigDecimal value) {
            addCriterion("trdAmt >", value, "trdamt");
            return (Criteria) this;
        }

        public Criteria andTrdamtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("trdAmt >=", value, "trdamt");
            return (Criteria) this;
        }

        public Criteria andTrdamtLessThan(BigDecimal value) {
            addCriterion("trdAmt <", value, "trdamt");
            return (Criteria) this;
        }

        public Criteria andTrdamtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("trdAmt <=", value, "trdamt");
            return (Criteria) this;
        }

        public Criteria andTrdamtIn(List<BigDecimal> values) {
            addCriterion("trdAmt in", values, "trdamt");
            return (Criteria) this;
        }

        public Criteria andTrdamtNotIn(List<BigDecimal> values) {
            addCriterion("trdAmt not in", values, "trdamt");
            return (Criteria) this;
        }

        public Criteria andTrdamtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("trdAmt between", value1, value2, "trdamt");
            return (Criteria) this;
        }

        public Criteria andTrdamtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("trdAmt not between", value1, value2, "trdamt");
            return (Criteria) this;
        }

        public Criteria andTrdtmIsNull() {
            addCriterion("trdTm is null");
            return (Criteria) this;
        }

        public Criteria andTrdtmIsNotNull() {
            addCriterion("trdTm is not null");
            return (Criteria) this;
        }

        public Criteria andTrdtmEqualTo(BigDecimal value) {
            addCriterion("trdTm =", value, "trdtm");
            return (Criteria) this;
        }

        public Criteria andTrdtmNotEqualTo(BigDecimal value) {
            addCriterion("trdTm <>", value, "trdtm");
            return (Criteria) this;
        }

        public Criteria andTrdtmGreaterThan(BigDecimal value) {
            addCriterion("trdTm >", value, "trdtm");
            return (Criteria) this;
        }

        public Criteria andTrdtmGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("trdTm >=", value, "trdtm");
            return (Criteria) this;
        }

        public Criteria andTrdtmLessThan(BigDecimal value) {
            addCriterion("trdTm <", value, "trdtm");
            return (Criteria) this;
        }

        public Criteria andTrdtmLessThanOrEqualTo(BigDecimal value) {
            addCriterion("trdTm <=", value, "trdtm");
            return (Criteria) this;
        }

        public Criteria andTrdtmIn(List<BigDecimal> values) {
            addCriterion("trdTm in", values, "trdtm");
            return (Criteria) this;
        }

        public Criteria andTrdtmNotIn(List<BigDecimal> values) {
            addCriterion("trdTm not in", values, "trdtm");
            return (Criteria) this;
        }

        public Criteria andTrdtmBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("trdTm between", value1, value2, "trdtm");
            return (Criteria) this;
        }

        public Criteria andTrdtmNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("trdTm not between", value1, value2, "trdtm");
            return (Criteria) this;
        }

        public Criteria andTrdtm1IsNull() {
            addCriterion("trdTm1 is null");
            return (Criteria) this;
        }

        public Criteria andTrdtm1IsNotNull() {
            addCriterion("trdTm1 is not null");
            return (Criteria) this;
        }

        public Criteria andTrdtm1EqualTo(BigDecimal value) {
            addCriterion("trdTm1 =", value, "trdtm1");
            return (Criteria) this;
        }

        public Criteria andTrdtm1NotEqualTo(BigDecimal value) {
            addCriterion("trdTm1 <>", value, "trdtm1");
            return (Criteria) this;
        }

        public Criteria andTrdtm1GreaterThan(BigDecimal value) {
            addCriterion("trdTm1 >", value, "trdtm1");
            return (Criteria) this;
        }

        public Criteria andTrdtm1GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("trdTm1 >=", value, "trdtm1");
            return (Criteria) this;
        }

        public Criteria andTrdtm1LessThan(BigDecimal value) {
            addCriterion("trdTm1 <", value, "trdtm1");
            return (Criteria) this;
        }

        public Criteria andTrdtm1LessThanOrEqualTo(BigDecimal value) {
            addCriterion("trdTm1 <=", value, "trdtm1");
            return (Criteria) this;
        }

        public Criteria andTrdtm1In(List<BigDecimal> values) {
            addCriterion("trdTm1 in", values, "trdtm1");
            return (Criteria) this;
        }

        public Criteria andTrdtm1NotIn(List<BigDecimal> values) {
            addCriterion("trdTm1 not in", values, "trdtm1");
            return (Criteria) this;
        }

        public Criteria andTrdtm1Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("trdTm1 between", value1, value2, "trdtm1");
            return (Criteria) this;
        }

        public Criteria andTrdtm1NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("trdTm1 not between", value1, value2, "trdtm1");
            return (Criteria) this;
        }

        public Criteria andMarketvalueIsNull() {
            addCriterion("marketValue is null");
            return (Criteria) this;
        }

        public Criteria andMarketvalueIsNotNull() {
            addCriterion("marketValue is not null");
            return (Criteria) this;
        }

        public Criteria andMarketvalueEqualTo(BigDecimal value) {
            addCriterion("marketValue =", value, "marketvalue");
            return (Criteria) this;
        }

        public Criteria andMarketvalueNotEqualTo(BigDecimal value) {
            addCriterion("marketValue <>", value, "marketvalue");
            return (Criteria) this;
        }

        public Criteria andMarketvalueGreaterThan(BigDecimal value) {
            addCriterion("marketValue >", value, "marketvalue");
            return (Criteria) this;
        }

        public Criteria andMarketvalueGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("marketValue >=", value, "marketvalue");
            return (Criteria) this;
        }

        public Criteria andMarketvalueLessThan(BigDecimal value) {
            addCriterion("marketValue <", value, "marketvalue");
            return (Criteria) this;
        }

        public Criteria andMarketvalueLessThanOrEqualTo(BigDecimal value) {
            addCriterion("marketValue <=", value, "marketvalue");
            return (Criteria) this;
        }

        public Criteria andMarketvalueIn(List<BigDecimal> values) {
            addCriterion("marketValue in", values, "marketvalue");
            return (Criteria) this;
        }

        public Criteria andMarketvalueNotIn(List<BigDecimal> values) {
            addCriterion("marketValue not in", values, "marketvalue");
            return (Criteria) this;
        }

        public Criteria andMarketvalueBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("marketValue between", value1, value2, "marketvalue");
            return (Criteria) this;
        }

        public Criteria andMarketvalueNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("marketValue not between", value1, value2, "marketvalue");
            return (Criteria) this;
        }

        public Criteria andNegotiablevalueIsNull() {
            addCriterion("negotiableValue is null");
            return (Criteria) this;
        }

        public Criteria andNegotiablevalueIsNotNull() {
            addCriterion("negotiableValue is not null");
            return (Criteria) this;
        }

        public Criteria andNegotiablevalueEqualTo(BigDecimal value) {
            addCriterion("negotiableValue =", value, "negotiablevalue");
            return (Criteria) this;
        }

        public Criteria andNegotiablevalueNotEqualTo(BigDecimal value) {
            addCriterion("negotiableValue <>", value, "negotiablevalue");
            return (Criteria) this;
        }

        public Criteria andNegotiablevalueGreaterThan(BigDecimal value) {
            addCriterion("negotiableValue >", value, "negotiablevalue");
            return (Criteria) this;
        }

        public Criteria andNegotiablevalueGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("negotiableValue >=", value, "negotiablevalue");
            return (Criteria) this;
        }

        public Criteria andNegotiablevalueLessThan(BigDecimal value) {
            addCriterion("negotiableValue <", value, "negotiablevalue");
            return (Criteria) this;
        }

        public Criteria andNegotiablevalueLessThanOrEqualTo(BigDecimal value) {
            addCriterion("negotiableValue <=", value, "negotiablevalue");
            return (Criteria) this;
        }

        public Criteria andNegotiablevalueIn(List<BigDecimal> values) {
            addCriterion("negotiableValue in", values, "negotiablevalue");
            return (Criteria) this;
        }

        public Criteria andNegotiablevalueNotIn(List<BigDecimal> values) {
            addCriterion("negotiableValue not in", values, "negotiablevalue");
            return (Criteria) this;
        }

        public Criteria andNegotiablevalueBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("negotiableValue between", value1, value2, "negotiablevalue");
            return (Criteria) this;
        }

        public Criteria andNegotiablevalueNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("negotiableValue not between", value1, value2, "negotiablevalue");
            return (Criteria) this;
        }

        public Criteria andProfitrateIsNull() {
            addCriterion("profitRate is null");
            return (Criteria) this;
        }

        public Criteria andProfitrateIsNotNull() {
            addCriterion("profitRate is not null");
            return (Criteria) this;
        }

        public Criteria andProfitrateEqualTo(BigDecimal value) {
            addCriterion("profitRate =", value, "profitrate");
            return (Criteria) this;
        }

        public Criteria andProfitrateNotEqualTo(BigDecimal value) {
            addCriterion("profitRate <>", value, "profitrate");
            return (Criteria) this;
        }

        public Criteria andProfitrateGreaterThan(BigDecimal value) {
            addCriterion("profitRate >", value, "profitrate");
            return (Criteria) this;
        }

        public Criteria andProfitrateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("profitRate >=", value, "profitrate");
            return (Criteria) this;
        }

        public Criteria andProfitrateLessThan(BigDecimal value) {
            addCriterion("profitRate <", value, "profitrate");
            return (Criteria) this;
        }

        public Criteria andProfitrateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("profitRate <=", value, "profitrate");
            return (Criteria) this;
        }

        public Criteria andProfitrateIn(List<BigDecimal> values) {
            addCriterion("profitRate in", values, "profitrate");
            return (Criteria) this;
        }

        public Criteria andProfitrateNotIn(List<BigDecimal> values) {
            addCriterion("profitRate not in", values, "profitrate");
            return (Criteria) this;
        }

        public Criteria andProfitrateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("profitRate between", value1, value2, "profitrate");
            return (Criteria) this;
        }

        public Criteria andProfitrateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("profitRate not between", value1, value2, "profitrate");
            return (Criteria) this;
        }

        public Criteria andProfitrate1IsNull() {
            addCriterion("profitRate1 is null");
            return (Criteria) this;
        }

        public Criteria andProfitrate1IsNotNull() {
            addCriterion("profitRate1 is not null");
            return (Criteria) this;
        }

        public Criteria andProfitrate1EqualTo(BigDecimal value) {
            addCriterion("profitRate1 =", value, "profitrate1");
            return (Criteria) this;
        }

        public Criteria andProfitrate1NotEqualTo(BigDecimal value) {
            addCriterion("profitRate1 <>", value, "profitrate1");
            return (Criteria) this;
        }

        public Criteria andProfitrate1GreaterThan(BigDecimal value) {
            addCriterion("profitRate1 >", value, "profitrate1");
            return (Criteria) this;
        }

        public Criteria andProfitrate1GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("profitRate1 >=", value, "profitrate1");
            return (Criteria) this;
        }

        public Criteria andProfitrate1LessThan(BigDecimal value) {
            addCriterion("profitRate1 <", value, "profitrate1");
            return (Criteria) this;
        }

        public Criteria andProfitrate1LessThanOrEqualTo(BigDecimal value) {
            addCriterion("profitRate1 <=", value, "profitrate1");
            return (Criteria) this;
        }

        public Criteria andProfitrate1In(List<BigDecimal> values) {
            addCriterion("profitRate1 in", values, "profitrate1");
            return (Criteria) this;
        }

        public Criteria andProfitrate1NotIn(List<BigDecimal> values) {
            addCriterion("profitRate1 not in", values, "profitrate1");
            return (Criteria) this;
        }

        public Criteria andProfitrate1Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("profitRate1 between", value1, value2, "profitrate1");
            return (Criteria) this;
        }

        public Criteria andProfitrate1NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("profitRate1 not between", value1, value2, "profitrate1");
            return (Criteria) this;
        }

        public Criteria andIstvolIsNull() {
            addCriterion("istVol is null");
            return (Criteria) this;
        }

        public Criteria andIstvolIsNotNull() {
            addCriterion("istVol is not null");
            return (Criteria) this;
        }

        public Criteria andIstvolEqualTo(BigDecimal value) {
            addCriterion("istVol =", value, "istvol");
            return (Criteria) this;
        }

        public Criteria andIstvolNotEqualTo(BigDecimal value) {
            addCriterion("istVol <>", value, "istvol");
            return (Criteria) this;
        }

        public Criteria andIstvolGreaterThan(BigDecimal value) {
            addCriterion("istVol >", value, "istvol");
            return (Criteria) this;
        }

        public Criteria andIstvolGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("istVol >=", value, "istvol");
            return (Criteria) this;
        }

        public Criteria andIstvolLessThan(BigDecimal value) {
            addCriterion("istVol <", value, "istvol");
            return (Criteria) this;
        }

        public Criteria andIstvolLessThanOrEqualTo(BigDecimal value) {
            addCriterion("istVol <=", value, "istvol");
            return (Criteria) this;
        }

        public Criteria andIstvolIn(List<BigDecimal> values) {
            addCriterion("istVol in", values, "istvol");
            return (Criteria) this;
        }

        public Criteria andIstvolNotIn(List<BigDecimal> values) {
            addCriterion("istVol not in", values, "istvol");
            return (Criteria) this;
        }

        public Criteria andIstvolBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("istVol between", value1, value2, "istvol");
            return (Criteria) this;
        }

        public Criteria andIstvolNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("istVol not between", value1, value2, "istvol");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jijin_daily
     *
     * @mbg.generated do_not_delete_during_merge Sun Oct 08 13:47:38 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jijin_daily
     *
     * @mbg.generated Sun Oct 08 13:47:38 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}